/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package order_v202406

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Order202406AddExternalOrderReferencesResponseDataErrors type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Order202406AddExternalOrderReferencesResponseDataErrors{}

// Order202406AddExternalOrderReferencesResponseDataErrors struct for Order202406AddExternalOrderReferencesResponseDataErrors
type Order202406AddExternalOrderReferencesResponseDataErrors struct {
    // A machine-readable response code that represents the request result.
    Code *string `json:"code,omitempty"`
    Detail *Order202406AddExternalOrderReferencesResponseDataErrorsDetail `json:"detail,omitempty"`
    // A human-readable message that describes the success or failure of the API request.
    Message *string `json:"message,omitempty"`
}

// NewOrder202406AddExternalOrderReferencesResponseDataErrors instantiates a new Order202406AddExternalOrderReferencesResponseDataErrors object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrder202406AddExternalOrderReferencesResponseDataErrors() *Order202406AddExternalOrderReferencesResponseDataErrors {
    this := Order202406AddExternalOrderReferencesResponseDataErrors{}
    return &this
}

// NewOrder202406AddExternalOrderReferencesResponseDataErrorsWithDefaults instantiates a new Order202406AddExternalOrderReferencesResponseDataErrors object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrder202406AddExternalOrderReferencesResponseDataErrorsWithDefaults() *Order202406AddExternalOrderReferencesResponseDataErrors {
    this := Order202406AddExternalOrderReferencesResponseDataErrors{}
    return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *Order202406AddExternalOrderReferencesResponseDataErrors) GetCode() string {
    if o == nil || utils.IsNil(o.Code) {
        var ret string
        return ret
    }
    return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Order202406AddExternalOrderReferencesResponseDataErrors) GetCodeOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Code) {
        return nil, false
    }
    return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *Order202406AddExternalOrderReferencesResponseDataErrors) HasCode() bool {
    if o != nil && !utils.IsNil(o.Code) {
        return true
    }

    return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *Order202406AddExternalOrderReferencesResponseDataErrors) SetCode(v string) {
    o.Code = &v
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *Order202406AddExternalOrderReferencesResponseDataErrors) GetDetail() Order202406AddExternalOrderReferencesResponseDataErrorsDetail {
    if o == nil || utils.IsNil(o.Detail) {
        var ret Order202406AddExternalOrderReferencesResponseDataErrorsDetail
        return ret
    }
    return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Order202406AddExternalOrderReferencesResponseDataErrors) GetDetailOk() (*Order202406AddExternalOrderReferencesResponseDataErrorsDetail, bool) {
    if o == nil || utils.IsNil(o.Detail) {
        return nil, false
    }
    return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *Order202406AddExternalOrderReferencesResponseDataErrors) HasDetail() bool {
    if o != nil && !utils.IsNil(o.Detail) {
        return true
    }

    return false
}

// SetDetail gets a reference to the given Order202406AddExternalOrderReferencesResponseDataErrorsDetail and assigns it to the Detail field.
func (o *Order202406AddExternalOrderReferencesResponseDataErrors) SetDetail(v Order202406AddExternalOrderReferencesResponseDataErrorsDetail) {
    o.Detail = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *Order202406AddExternalOrderReferencesResponseDataErrors) GetMessage() string {
    if o == nil || utils.IsNil(o.Message) {
        var ret string
        return ret
    }
    return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Order202406AddExternalOrderReferencesResponseDataErrors) GetMessageOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Message) {
        return nil, false
    }
    return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *Order202406AddExternalOrderReferencesResponseDataErrors) HasMessage() bool {
    if o != nil && !utils.IsNil(o.Message) {
        return true
    }

    return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *Order202406AddExternalOrderReferencesResponseDataErrors) SetMessage(v string) {
    o.Message = &v
}

func (o Order202406AddExternalOrderReferencesResponseDataErrors) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Order202406AddExternalOrderReferencesResponseDataErrors) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Code) {
        toSerialize["code"] = o.Code
    }
    if !utils.IsNil(o.Detail) {
        toSerialize["detail"] = o.Detail
    }
    if !utils.IsNil(o.Message) {
        toSerialize["message"] = o.Message
    }
    return toSerialize, nil
}

type NullableOrder202406AddExternalOrderReferencesResponseDataErrors struct {
	value *Order202406AddExternalOrderReferencesResponseDataErrors
	isSet bool
}

func (v NullableOrder202406AddExternalOrderReferencesResponseDataErrors) Get() *Order202406AddExternalOrderReferencesResponseDataErrors {
	return v.value
}

func (v *NullableOrder202406AddExternalOrderReferencesResponseDataErrors) Set(val *Order202406AddExternalOrderReferencesResponseDataErrors) {
	v.value = val
	v.isSet = true
}

func (v NullableOrder202406AddExternalOrderReferencesResponseDataErrors) IsSet() bool {
	return v.isSet
}

func (v *NullableOrder202406AddExternalOrderReferencesResponseDataErrors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrder202406AddExternalOrderReferencesResponseDataErrors(val *Order202406AddExternalOrderReferencesResponseDataErrors) *NullableOrder202406AddExternalOrderReferencesResponseDataErrors {
	return &NullableOrder202406AddExternalOrderReferencesResponseDataErrors{value: val, isSet: true}
}

func (v NullableOrder202406AddExternalOrderReferencesResponseDataErrors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrder202406AddExternalOrderReferencesResponseDataErrors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


