/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202309CheckProductListingRequestBodyCertifications type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202309CheckProductListingRequestBodyCertifications{}

// Product202309CheckProductListingRequestBodyCertifications struct for Product202309CheckProductListingRequestBodyCertifications
type Product202309CheckProductListingRequestBodyCertifications struct {
    // The expiration date of this certification expressed in unix timestamp (seconds) UTC+0.  This field may be required for certain certifications. Use the [Get Category Rules API](https://partner.tiktokshop.com/docv2/page/6509c0febace3e02b74594a9) to find out the requirements.
    ExpirationDate *int64 `json:"expiration_date,omitempty"`
    // A list of certification related files.
    Files []Product202309CheckProductListingRequestBodyCertificationsFiles `json:"files,omitempty"`
    // The ID to identify the type of certification required for the product category. Retrieve this value from the [Get Category Rules API](https://partner.tiktokshop.com/docv2/page/6509c0febace3e02b74594a9). 
    Id *string `json:"id,omitempty"`
    // A list of certification related images.
    Images []Product202309CheckProductListingRequestBodyCertificationsImages `json:"images,omitempty"`
}

// NewProduct202309CheckProductListingRequestBodyCertifications instantiates a new Product202309CheckProductListingRequestBodyCertifications object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202309CheckProductListingRequestBodyCertifications() *Product202309CheckProductListingRequestBodyCertifications {
    this := Product202309CheckProductListingRequestBodyCertifications{}
    return &this
}

// NewProduct202309CheckProductListingRequestBodyCertificationsWithDefaults instantiates a new Product202309CheckProductListingRequestBodyCertifications object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202309CheckProductListingRequestBodyCertificationsWithDefaults() *Product202309CheckProductListingRequestBodyCertifications {
    this := Product202309CheckProductListingRequestBodyCertifications{}
    return &this
}

// GetExpirationDate returns the ExpirationDate field value if set, zero value otherwise.
func (o *Product202309CheckProductListingRequestBodyCertifications) GetExpirationDate() int64 {
    if o == nil || utils.IsNil(o.ExpirationDate) {
        var ret int64
        return ret
    }
    return *o.ExpirationDate
}

// GetExpirationDateOk returns a tuple with the ExpirationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309CheckProductListingRequestBodyCertifications) GetExpirationDateOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.ExpirationDate) {
        return nil, false
    }
    return o.ExpirationDate, true
}

// HasExpirationDate returns a boolean if a field has been set.
func (o *Product202309CheckProductListingRequestBodyCertifications) HasExpirationDate() bool {
    if o != nil && !utils.IsNil(o.ExpirationDate) {
        return true
    }

    return false
}

// SetExpirationDate gets a reference to the given int64 and assigns it to the ExpirationDate field.
func (o *Product202309CheckProductListingRequestBodyCertifications) SetExpirationDate(v int64) {
    o.ExpirationDate = &v
}

// GetFiles returns the Files field value if set, zero value otherwise.
func (o *Product202309CheckProductListingRequestBodyCertifications) GetFiles() []Product202309CheckProductListingRequestBodyCertificationsFiles {
    if o == nil || utils.IsNil(o.Files) {
        var ret []Product202309CheckProductListingRequestBodyCertificationsFiles
        return ret
    }
    return o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309CheckProductListingRequestBodyCertifications) GetFilesOk() ([]Product202309CheckProductListingRequestBodyCertificationsFiles, bool) {
    if o == nil || utils.IsNil(o.Files) {
        return nil, false
    }
    return o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *Product202309CheckProductListingRequestBodyCertifications) HasFiles() bool {
    if o != nil && !utils.IsNil(o.Files) {
        return true
    }

    return false
}

// SetFiles gets a reference to the given []Product202309CheckProductListingRequestBodyCertificationsFiles and assigns it to the Files field.
func (o *Product202309CheckProductListingRequestBodyCertifications) SetFiles(v []Product202309CheckProductListingRequestBodyCertificationsFiles) {
    o.Files = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Product202309CheckProductListingRequestBodyCertifications) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309CheckProductListingRequestBodyCertifications) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Product202309CheckProductListingRequestBodyCertifications) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Product202309CheckProductListingRequestBodyCertifications) SetId(v string) {
    o.Id = &v
}

// GetImages returns the Images field value if set, zero value otherwise.
func (o *Product202309CheckProductListingRequestBodyCertifications) GetImages() []Product202309CheckProductListingRequestBodyCertificationsImages {
    if o == nil || utils.IsNil(o.Images) {
        var ret []Product202309CheckProductListingRequestBodyCertificationsImages
        return ret
    }
    return o.Images
}

// GetImagesOk returns a tuple with the Images field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309CheckProductListingRequestBodyCertifications) GetImagesOk() ([]Product202309CheckProductListingRequestBodyCertificationsImages, bool) {
    if o == nil || utils.IsNil(o.Images) {
        return nil, false
    }
    return o.Images, true
}

// HasImages returns a boolean if a field has been set.
func (o *Product202309CheckProductListingRequestBodyCertifications) HasImages() bool {
    if o != nil && !utils.IsNil(o.Images) {
        return true
    }

    return false
}

// SetImages gets a reference to the given []Product202309CheckProductListingRequestBodyCertificationsImages and assigns it to the Images field.
func (o *Product202309CheckProductListingRequestBodyCertifications) SetImages(v []Product202309CheckProductListingRequestBodyCertificationsImages) {
    o.Images = v
}

func (o Product202309CheckProductListingRequestBodyCertifications) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202309CheckProductListingRequestBodyCertifications) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.ExpirationDate) {
        toSerialize["expiration_date"] = o.ExpirationDate
    }
    if !utils.IsNil(o.Files) {
        toSerialize["files"] = o.Files
    }
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }
    if !utils.IsNil(o.Images) {
        toSerialize["images"] = o.Images
    }
    return toSerialize, nil
}

type NullableProduct202309CheckProductListingRequestBodyCertifications struct {
	value *Product202309CheckProductListingRequestBodyCertifications
	isSet bool
}

func (v NullableProduct202309CheckProductListingRequestBodyCertifications) Get() *Product202309CheckProductListingRequestBodyCertifications {
	return v.value
}

func (v *NullableProduct202309CheckProductListingRequestBodyCertifications) Set(val *Product202309CheckProductListingRequestBodyCertifications) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202309CheckProductListingRequestBodyCertifications) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202309CheckProductListingRequestBodyCertifications) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202309CheckProductListingRequestBodyCertifications(val *Product202309CheckProductListingRequestBodyCertifications) *NullableProduct202309CheckProductListingRequestBodyCertifications {
	return &NullableProduct202309CheckProductListingRequestBodyCertifications{value: val, isSet: true}
}

func (v NullableProduct202309CheckProductListingRequestBodyCertifications) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202309CheckProductListingRequestBodyCertifications) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


