/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts{}

// Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts struct for Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts
type Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts struct {
    // The suggested intelligent text.
    Text *string `json:"text,omitempty"`
}

// NewProduct202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts instantiates a new Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts() *Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts {
    this := Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts{}
    return &this
}

// NewProduct202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTextsWithDefaults instantiates a new Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTextsWithDefaults() *Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts {
    this := Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts{}
    return &this
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts) GetText() string {
    if o == nil || utils.IsNil(o.Text) {
        var ret string
        return ret
    }
    return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts) GetTextOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Text) {
        return nil, false
    }
    return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts) HasText() bool {
    if o != nil && !utils.IsNil(o.Text) {
        return true
    }

    return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts) SetText(v string) {
    o.Text = &v
}

func (o Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Text) {
        toSerialize["text"] = o.Text
    }
    return toSerialize, nil
}

type NullableProduct202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts struct {
	value *Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts
	isSet bool
}

func (v NullableProduct202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts) Get() *Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts {
	return v.value
}

func (v *NullableProduct202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts) Set(val *Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts(val *Product202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts) *NullableProduct202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts {
	return &NullableProduct202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts{value: val, isSet: true}
}

func (v NullableProduct202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202309CheckProductListingResponseDataDiagnosesSuggestionsSmartTexts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


