/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202309CreateGlobalProductRequestBodySizeChart type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202309CreateGlobalProductRequestBodySizeChart{}

// Product202309CreateGlobalProductRequestBodySizeChart struct for Product202309CreateGlobalProductRequestBodySizeChart
type Product202309CreateGlobalProductRequestBodySizeChart struct {
    Image *Product202309CreateGlobalProductRequestBodySizeChartImage `json:"image,omitempty"`
    Template *Product202309CreateGlobalProductRequestBodySizeChartTemplate `json:"template,omitempty"`
}

// NewProduct202309CreateGlobalProductRequestBodySizeChart instantiates a new Product202309CreateGlobalProductRequestBodySizeChart object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202309CreateGlobalProductRequestBodySizeChart() *Product202309CreateGlobalProductRequestBodySizeChart {
    this := Product202309CreateGlobalProductRequestBodySizeChart{}
    return &this
}

// NewProduct202309CreateGlobalProductRequestBodySizeChartWithDefaults instantiates a new Product202309CreateGlobalProductRequestBodySizeChart object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202309CreateGlobalProductRequestBodySizeChartWithDefaults() *Product202309CreateGlobalProductRequestBodySizeChart {
    this := Product202309CreateGlobalProductRequestBodySizeChart{}
    return &this
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *Product202309CreateGlobalProductRequestBodySizeChart) GetImage() Product202309CreateGlobalProductRequestBodySizeChartImage {
    if o == nil || utils.IsNil(o.Image) {
        var ret Product202309CreateGlobalProductRequestBodySizeChartImage
        return ret
    }
    return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309CreateGlobalProductRequestBodySizeChart) GetImageOk() (*Product202309CreateGlobalProductRequestBodySizeChartImage, bool) {
    if o == nil || utils.IsNil(o.Image) {
        return nil, false
    }
    return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *Product202309CreateGlobalProductRequestBodySizeChart) HasImage() bool {
    if o != nil && !utils.IsNil(o.Image) {
        return true
    }

    return false
}

// SetImage gets a reference to the given Product202309CreateGlobalProductRequestBodySizeChartImage and assigns it to the Image field.
func (o *Product202309CreateGlobalProductRequestBodySizeChart) SetImage(v Product202309CreateGlobalProductRequestBodySizeChartImage) {
    o.Image = &v
}

// GetTemplate returns the Template field value if set, zero value otherwise.
func (o *Product202309CreateGlobalProductRequestBodySizeChart) GetTemplate() Product202309CreateGlobalProductRequestBodySizeChartTemplate {
    if o == nil || utils.IsNil(o.Template) {
        var ret Product202309CreateGlobalProductRequestBodySizeChartTemplate
        return ret
    }
    return *o.Template
}

// GetTemplateOk returns a tuple with the Template field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309CreateGlobalProductRequestBodySizeChart) GetTemplateOk() (*Product202309CreateGlobalProductRequestBodySizeChartTemplate, bool) {
    if o == nil || utils.IsNil(o.Template) {
        return nil, false
    }
    return o.Template, true
}

// HasTemplate returns a boolean if a field has been set.
func (o *Product202309CreateGlobalProductRequestBodySizeChart) HasTemplate() bool {
    if o != nil && !utils.IsNil(o.Template) {
        return true
    }

    return false
}

// SetTemplate gets a reference to the given Product202309CreateGlobalProductRequestBodySizeChartTemplate and assigns it to the Template field.
func (o *Product202309CreateGlobalProductRequestBodySizeChart) SetTemplate(v Product202309CreateGlobalProductRequestBodySizeChartTemplate) {
    o.Template = &v
}

func (o Product202309CreateGlobalProductRequestBodySizeChart) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202309CreateGlobalProductRequestBodySizeChart) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Image) {
        toSerialize["image"] = o.Image
    }
    if !utils.IsNil(o.Template) {
        toSerialize["template"] = o.Template
    }
    return toSerialize, nil
}

type NullableProduct202309CreateGlobalProductRequestBodySizeChart struct {
	value *Product202309CreateGlobalProductRequestBodySizeChart
	isSet bool
}

func (v NullableProduct202309CreateGlobalProductRequestBodySizeChart) Get() *Product202309CreateGlobalProductRequestBodySizeChart {
	return v.value
}

func (v *NullableProduct202309CreateGlobalProductRequestBodySizeChart) Set(val *Product202309CreateGlobalProductRequestBodySizeChart) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202309CreateGlobalProductRequestBodySizeChart) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202309CreateGlobalProductRequestBodySizeChart) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202309CreateGlobalProductRequestBodySizeChart(val *Product202309CreateGlobalProductRequestBodySizeChart) *NullableProduct202309CreateGlobalProductRequestBodySizeChart {
	return &NullableProduct202309CreateGlobalProductRequestBodySizeChart{value: val, isSet: true}
}

func (v NullableProduct202309CreateGlobalProductRequestBodySizeChart) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202309CreateGlobalProductRequestBodySizeChart) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


