/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202309CreateProductRequestBodySizeChart type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202309CreateProductRequestBodySizeChart{}

// Product202309CreateProductRequestBodySizeChart struct for Product202309CreateProductRequestBodySizeChart
type Product202309CreateProductRequestBodySizeChart struct {
    Image *Product202309CreateProductRequestBodySizeChartImage `json:"image,omitempty"`
    Template *Product202309CreateProductRequestBodySizeChartTemplate `json:"template,omitempty"`
}

// NewProduct202309CreateProductRequestBodySizeChart instantiates a new Product202309CreateProductRequestBodySizeChart object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202309CreateProductRequestBodySizeChart() *Product202309CreateProductRequestBodySizeChart {
    this := Product202309CreateProductRequestBodySizeChart{}
    return &this
}

// NewProduct202309CreateProductRequestBodySizeChartWithDefaults instantiates a new Product202309CreateProductRequestBodySizeChart object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202309CreateProductRequestBodySizeChartWithDefaults() *Product202309CreateProductRequestBodySizeChart {
    this := Product202309CreateProductRequestBodySizeChart{}
    return &this
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *Product202309CreateProductRequestBodySizeChart) GetImage() Product202309CreateProductRequestBodySizeChartImage {
    if o == nil || utils.IsNil(o.Image) {
        var ret Product202309CreateProductRequestBodySizeChartImage
        return ret
    }
    return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309CreateProductRequestBodySizeChart) GetImageOk() (*Product202309CreateProductRequestBodySizeChartImage, bool) {
    if o == nil || utils.IsNil(o.Image) {
        return nil, false
    }
    return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *Product202309CreateProductRequestBodySizeChart) HasImage() bool {
    if o != nil && !utils.IsNil(o.Image) {
        return true
    }

    return false
}

// SetImage gets a reference to the given Product202309CreateProductRequestBodySizeChartImage and assigns it to the Image field.
func (o *Product202309CreateProductRequestBodySizeChart) SetImage(v Product202309CreateProductRequestBodySizeChartImage) {
    o.Image = &v
}

// GetTemplate returns the Template field value if set, zero value otherwise.
func (o *Product202309CreateProductRequestBodySizeChart) GetTemplate() Product202309CreateProductRequestBodySizeChartTemplate {
    if o == nil || utils.IsNil(o.Template) {
        var ret Product202309CreateProductRequestBodySizeChartTemplate
        return ret
    }
    return *o.Template
}

// GetTemplateOk returns a tuple with the Template field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309CreateProductRequestBodySizeChart) GetTemplateOk() (*Product202309CreateProductRequestBodySizeChartTemplate, bool) {
    if o == nil || utils.IsNil(o.Template) {
        return nil, false
    }
    return o.Template, true
}

// HasTemplate returns a boolean if a field has been set.
func (o *Product202309CreateProductRequestBodySizeChart) HasTemplate() bool {
    if o != nil && !utils.IsNil(o.Template) {
        return true
    }

    return false
}

// SetTemplate gets a reference to the given Product202309CreateProductRequestBodySizeChartTemplate and assigns it to the Template field.
func (o *Product202309CreateProductRequestBodySizeChart) SetTemplate(v Product202309CreateProductRequestBodySizeChartTemplate) {
    o.Template = &v
}

func (o Product202309CreateProductRequestBodySizeChart) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202309CreateProductRequestBodySizeChart) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Image) {
        toSerialize["image"] = o.Image
    }
    if !utils.IsNil(o.Template) {
        toSerialize["template"] = o.Template
    }
    return toSerialize, nil
}

type NullableProduct202309CreateProductRequestBodySizeChart struct {
	value *Product202309CreateProductRequestBodySizeChart
	isSet bool
}

func (v NullableProduct202309CreateProductRequestBodySizeChart) Get() *Product202309CreateProductRequestBodySizeChart {
	return v.value
}

func (v *NullableProduct202309CreateProductRequestBodySizeChart) Set(val *Product202309CreateProductRequestBodySizeChart) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202309CreateProductRequestBodySizeChart) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202309CreateProductRequestBodySizeChart) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202309CreateProductRequestBodySizeChart(val *Product202309CreateProductRequestBodySizeChart) *NullableProduct202309CreateProductRequestBodySizeChart {
	return &NullableProduct202309CreateProductRequestBodySizeChart{value: val, isSet: true}
}

func (v NullableProduct202309CreateProductRequestBodySizeChart) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202309CreateProductRequestBodySizeChart) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


