/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202309EditProductRequestBodyProductAttributesValues type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202309EditProductRequestBodyProductAttributesValues{}

// Product202309EditProductRequestBodyProductAttributesValues struct for Product202309EditProductRequestBodyProductAttributesValues
type Product202309EditProductRequestBodyProductAttributesValues struct {
    // The ID of the product attribute value. This is either a built-in product attribute value ID from [Get Attributes API](https://partner.tiktokshop.com/docv2/page/6509c5784a0bb702c0561cc8) or a custom product attribute value ID returned after calling [Create Product API](https://partner.tiktokshop.com/docv2/page/6502fc8da57708028b42b18a).
    Id *string `json:"id,omitempty"`
    // A self-defined custom product attribute value if the built-in values do not satisfy your needs. The system will auto-generate an ID after editing.  **Note**:  - No duplicates allowed under the same attribute. - Max length: 2000 characters
    Name *string `json:"name,omitempty"`
}

// NewProduct202309EditProductRequestBodyProductAttributesValues instantiates a new Product202309EditProductRequestBodyProductAttributesValues object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202309EditProductRequestBodyProductAttributesValues() *Product202309EditProductRequestBodyProductAttributesValues {
    this := Product202309EditProductRequestBodyProductAttributesValues{}
    return &this
}

// NewProduct202309EditProductRequestBodyProductAttributesValuesWithDefaults instantiates a new Product202309EditProductRequestBodyProductAttributesValues object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202309EditProductRequestBodyProductAttributesValuesWithDefaults() *Product202309EditProductRequestBodyProductAttributesValues {
    this := Product202309EditProductRequestBodyProductAttributesValues{}
    return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Product202309EditProductRequestBodyProductAttributesValues) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditProductRequestBodyProductAttributesValues) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Product202309EditProductRequestBodyProductAttributesValues) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Product202309EditProductRequestBodyProductAttributesValues) SetId(v string) {
    o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Product202309EditProductRequestBodyProductAttributesValues) GetName() string {
    if o == nil || utils.IsNil(o.Name) {
        var ret string
        return ret
    }
    return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditProductRequestBodyProductAttributesValues) GetNameOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Name) {
        return nil, false
    }
    return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Product202309EditProductRequestBodyProductAttributesValues) HasName() bool {
    if o != nil && !utils.IsNil(o.Name) {
        return true
    }

    return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Product202309EditProductRequestBodyProductAttributesValues) SetName(v string) {
    o.Name = &v
}

func (o Product202309EditProductRequestBodyProductAttributesValues) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202309EditProductRequestBodyProductAttributesValues) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }
    if !utils.IsNil(o.Name) {
        toSerialize["name"] = o.Name
    }
    return toSerialize, nil
}

type NullableProduct202309EditProductRequestBodyProductAttributesValues struct {
	value *Product202309EditProductRequestBodyProductAttributesValues
	isSet bool
}

func (v NullableProduct202309EditProductRequestBodyProductAttributesValues) Get() *Product202309EditProductRequestBodyProductAttributesValues {
	return v.value
}

func (v *NullableProduct202309EditProductRequestBodyProductAttributesValues) Set(val *Product202309EditProductRequestBodyProductAttributesValues) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202309EditProductRequestBodyProductAttributesValues) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202309EditProductRequestBodyProductAttributesValues) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202309EditProductRequestBodyProductAttributesValues(val *Product202309EditProductRequestBodyProductAttributesValues) *NullableProduct202309EditProductRequestBodyProductAttributesValues {
	return &NullableProduct202309EditProductRequestBodyProductAttributesValues{value: val, isSet: true}
}

func (v NullableProduct202309EditProductRequestBodyProductAttributesValues) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202309EditProductRequestBodyProductAttributesValues) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


