/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202309EditProductResponseDataSkus type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202309EditProductResponseDataSkus{}

// Product202309EditProductResponseDataSkus struct for Product202309EditProductResponseDataSkus
type Product202309EditProductResponseDataSkus struct {
    // An external identifier used in an external ecommerce platform. This is used to associate the SKU between TikTok Shop and the external ecommerce platform. 
    ExternalSkuId *string `json:"external_sku_id,omitempty"`
    // The SKU ID generated by TikTok Shop. One product can contain multiple SKU IDs.
    Id *string `json:"id,omitempty"`
    // A list of attributes  (e.g. size, color, length) that define each variant of a product.
    SalesAttributes []Product202309EditProductResponseDataSkusSalesAttributes `json:"sales_attributes,omitempty"`
    // An internal code/name for managing SKUs, not visible to buyers.  
    SellerSku *string `json:"seller_sku,omitempty"`
}

// NewProduct202309EditProductResponseDataSkus instantiates a new Product202309EditProductResponseDataSkus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202309EditProductResponseDataSkus() *Product202309EditProductResponseDataSkus {
    this := Product202309EditProductResponseDataSkus{}
    return &this
}

// NewProduct202309EditProductResponseDataSkusWithDefaults instantiates a new Product202309EditProductResponseDataSkus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202309EditProductResponseDataSkusWithDefaults() *Product202309EditProductResponseDataSkus {
    this := Product202309EditProductResponseDataSkus{}
    return &this
}

// GetExternalSkuId returns the ExternalSkuId field value if set, zero value otherwise.
func (o *Product202309EditProductResponseDataSkus) GetExternalSkuId() string {
    if o == nil || utils.IsNil(o.ExternalSkuId) {
        var ret string
        return ret
    }
    return *o.ExternalSkuId
}

// GetExternalSkuIdOk returns a tuple with the ExternalSkuId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditProductResponseDataSkus) GetExternalSkuIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.ExternalSkuId) {
        return nil, false
    }
    return o.ExternalSkuId, true
}

// HasExternalSkuId returns a boolean if a field has been set.
func (o *Product202309EditProductResponseDataSkus) HasExternalSkuId() bool {
    if o != nil && !utils.IsNil(o.ExternalSkuId) {
        return true
    }

    return false
}

// SetExternalSkuId gets a reference to the given string and assigns it to the ExternalSkuId field.
func (o *Product202309EditProductResponseDataSkus) SetExternalSkuId(v string) {
    o.ExternalSkuId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Product202309EditProductResponseDataSkus) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditProductResponseDataSkus) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Product202309EditProductResponseDataSkus) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Product202309EditProductResponseDataSkus) SetId(v string) {
    o.Id = &v
}

// GetSalesAttributes returns the SalesAttributes field value if set, zero value otherwise.
func (o *Product202309EditProductResponseDataSkus) GetSalesAttributes() []Product202309EditProductResponseDataSkusSalesAttributes {
    if o == nil || utils.IsNil(o.SalesAttributes) {
        var ret []Product202309EditProductResponseDataSkusSalesAttributes
        return ret
    }
    return o.SalesAttributes
}

// GetSalesAttributesOk returns a tuple with the SalesAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditProductResponseDataSkus) GetSalesAttributesOk() ([]Product202309EditProductResponseDataSkusSalesAttributes, bool) {
    if o == nil || utils.IsNil(o.SalesAttributes) {
        return nil, false
    }
    return o.SalesAttributes, true
}

// HasSalesAttributes returns a boolean if a field has been set.
func (o *Product202309EditProductResponseDataSkus) HasSalesAttributes() bool {
    if o != nil && !utils.IsNil(o.SalesAttributes) {
        return true
    }

    return false
}

// SetSalesAttributes gets a reference to the given []Product202309EditProductResponseDataSkusSalesAttributes and assigns it to the SalesAttributes field.
func (o *Product202309EditProductResponseDataSkus) SetSalesAttributes(v []Product202309EditProductResponseDataSkusSalesAttributes) {
    o.SalesAttributes = v
}

// GetSellerSku returns the SellerSku field value if set, zero value otherwise.
func (o *Product202309EditProductResponseDataSkus) GetSellerSku() string {
    if o == nil || utils.IsNil(o.SellerSku) {
        var ret string
        return ret
    }
    return *o.SellerSku
}

// GetSellerSkuOk returns a tuple with the SellerSku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditProductResponseDataSkus) GetSellerSkuOk() (*string, bool) {
    if o == nil || utils.IsNil(o.SellerSku) {
        return nil, false
    }
    return o.SellerSku, true
}

// HasSellerSku returns a boolean if a field has been set.
func (o *Product202309EditProductResponseDataSkus) HasSellerSku() bool {
    if o != nil && !utils.IsNil(o.SellerSku) {
        return true
    }

    return false
}

// SetSellerSku gets a reference to the given string and assigns it to the SellerSku field.
func (o *Product202309EditProductResponseDataSkus) SetSellerSku(v string) {
    o.SellerSku = &v
}

func (o Product202309EditProductResponseDataSkus) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202309EditProductResponseDataSkus) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.ExternalSkuId) {
        toSerialize["external_sku_id"] = o.ExternalSkuId
    }
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }
    if !utils.IsNil(o.SalesAttributes) {
        toSerialize["sales_attributes"] = o.SalesAttributes
    }
    if !utils.IsNil(o.SellerSku) {
        toSerialize["seller_sku"] = o.SellerSku
    }
    return toSerialize, nil
}

type NullableProduct202309EditProductResponseDataSkus struct {
	value *Product202309EditProductResponseDataSkus
	isSet bool
}

func (v NullableProduct202309EditProductResponseDataSkus) Get() *Product202309EditProductResponseDataSkus {
	return v.value
}

func (v *NullableProduct202309EditProductResponseDataSkus) Set(val *Product202309EditProductResponseDataSkus) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202309EditProductResponseDataSkus) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202309EditProductResponseDataSkus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202309EditProductResponseDataSkus(val *Product202309EditProductResponseDataSkus) *NullableProduct202309EditProductResponseDataSkus {
	return &NullableProduct202309EditProductResponseDataSkus{value: val, isSet: true}
}

func (v NullableProduct202309EditProductResponseDataSkus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202309EditProductResponseDataSkus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


