/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202309EditGlobalProductRequestBodyCertifications type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202309EditGlobalProductRequestBodyCertifications{}

// Product202309EditGlobalProductRequestBodyCertifications struct for Product202309EditGlobalProductRequestBodyCertifications
type Product202309EditGlobalProductRequestBodyCertifications struct {
    // A list of certification related files.
    Files []Product202309EditGlobalProductRequestBodyCertificationsFiles `json:"files,omitempty"`
    // The ID to identify the type of certification required for the product category. Retrieve this value from the [Get Global Category Rules API](https://partner.tiktokshop.com/docv2/page/650a056df1fd3102b91b5b8e). 
    Id *string `json:"id,omitempty"`
    // A list of certification related images.
    Images []Product202309EditGlobalProductRequestBodyCertificationsImages `json:"images,omitempty"`
}

// NewProduct202309EditGlobalProductRequestBodyCertifications instantiates a new Product202309EditGlobalProductRequestBodyCertifications object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202309EditGlobalProductRequestBodyCertifications() *Product202309EditGlobalProductRequestBodyCertifications {
    this := Product202309EditGlobalProductRequestBodyCertifications{}
    return &this
}

// NewProduct202309EditGlobalProductRequestBodyCertificationsWithDefaults instantiates a new Product202309EditGlobalProductRequestBodyCertifications object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202309EditGlobalProductRequestBodyCertificationsWithDefaults() *Product202309EditGlobalProductRequestBodyCertifications {
    this := Product202309EditGlobalProductRequestBodyCertifications{}
    return &this
}

// GetFiles returns the Files field value if set, zero value otherwise.
func (o *Product202309EditGlobalProductRequestBodyCertifications) GetFiles() []Product202309EditGlobalProductRequestBodyCertificationsFiles {
    if o == nil || utils.IsNil(o.Files) {
        var ret []Product202309EditGlobalProductRequestBodyCertificationsFiles
        return ret
    }
    return o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditGlobalProductRequestBodyCertifications) GetFilesOk() ([]Product202309EditGlobalProductRequestBodyCertificationsFiles, bool) {
    if o == nil || utils.IsNil(o.Files) {
        return nil, false
    }
    return o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *Product202309EditGlobalProductRequestBodyCertifications) HasFiles() bool {
    if o != nil && !utils.IsNil(o.Files) {
        return true
    }

    return false
}

// SetFiles gets a reference to the given []Product202309EditGlobalProductRequestBodyCertificationsFiles and assigns it to the Files field.
func (o *Product202309EditGlobalProductRequestBodyCertifications) SetFiles(v []Product202309EditGlobalProductRequestBodyCertificationsFiles) {
    o.Files = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Product202309EditGlobalProductRequestBodyCertifications) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditGlobalProductRequestBodyCertifications) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Product202309EditGlobalProductRequestBodyCertifications) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Product202309EditGlobalProductRequestBodyCertifications) SetId(v string) {
    o.Id = &v
}

// GetImages returns the Images field value if set, zero value otherwise.
func (o *Product202309EditGlobalProductRequestBodyCertifications) GetImages() []Product202309EditGlobalProductRequestBodyCertificationsImages {
    if o == nil || utils.IsNil(o.Images) {
        var ret []Product202309EditGlobalProductRequestBodyCertificationsImages
        return ret
    }
    return o.Images
}

// GetImagesOk returns a tuple with the Images field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditGlobalProductRequestBodyCertifications) GetImagesOk() ([]Product202309EditGlobalProductRequestBodyCertificationsImages, bool) {
    if o == nil || utils.IsNil(o.Images) {
        return nil, false
    }
    return o.Images, true
}

// HasImages returns a boolean if a field has been set.
func (o *Product202309EditGlobalProductRequestBodyCertifications) HasImages() bool {
    if o != nil && !utils.IsNil(o.Images) {
        return true
    }

    return false
}

// SetImages gets a reference to the given []Product202309EditGlobalProductRequestBodyCertificationsImages and assigns it to the Images field.
func (o *Product202309EditGlobalProductRequestBodyCertifications) SetImages(v []Product202309EditGlobalProductRequestBodyCertificationsImages) {
    o.Images = v
}

func (o Product202309EditGlobalProductRequestBodyCertifications) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202309EditGlobalProductRequestBodyCertifications) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Files) {
        toSerialize["files"] = o.Files
    }
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }
    if !utils.IsNil(o.Images) {
        toSerialize["images"] = o.Images
    }
    return toSerialize, nil
}

type NullableProduct202309EditGlobalProductRequestBodyCertifications struct {
	value *Product202309EditGlobalProductRequestBodyCertifications
	isSet bool
}

func (v NullableProduct202309EditGlobalProductRequestBodyCertifications) Get() *Product202309EditGlobalProductRequestBodyCertifications {
	return v.value
}

func (v *NullableProduct202309EditGlobalProductRequestBodyCertifications) Set(val *Product202309EditGlobalProductRequestBodyCertifications) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202309EditGlobalProductRequestBodyCertifications) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202309EditGlobalProductRequestBodyCertifications) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202309EditGlobalProductRequestBodyCertifications(val *Product202309EditGlobalProductRequestBodyCertifications) *NullableProduct202309EditGlobalProductRequestBodyCertifications {
	return &NullableProduct202309EditGlobalProductRequestBodyCertifications{value: val, isSet: true}
}

func (v NullableProduct202309EditGlobalProductRequestBodyCertifications) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202309EditGlobalProductRequestBodyCertifications) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


