/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202309EditGlobalProductRequestBody type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202309EditGlobalProductRequestBody{}

// Product202309EditGlobalProductRequestBody struct for Product202309EditGlobalProductRequestBody
type Product202309EditGlobalProductRequestBody struct {
    // The ID of the brand of this product.  **Note**: Unauthorized brands won't be displayed on TikTok Shop.
    BrandId *string `json:"brand_id,omitempty"`
    // The ID of the category of this product.  - It must be a leaf category that corresponds to the category tree type specified in the `category_version` property.  - It must be a main category (`categories.permission_statuses=AVAILABLE` in [Get Global Categories API](650a03f8f1fd3102b91b338a)). **Note**: Refer to TikTok Shop Academy for information on product category restrictions.
    CategoryId *string `json:"category_id,omitempty"`
    // The category tree version to assign this product to. Possible values based on region: - US: `v2`, represents the 7-level category tree.   **Important**: If the seller account contains an active US shop, you must pass `v2` when using this API. - Other regions: `v1`, represents the 3-level category tree. Default: `v1`
    CategoryVersion *string `json:"category_version,omitempty"`
    // The list of certifications for your product. Max count: 10  As per TikTok Shop guidelines, certifications are required for certain restricted product categories. Retrieve the certification requirements for your product from the  [Get Global Category Rules API](https://partner.tiktokshop.com/docv2/page/650a056df1fd3102b91b5b8e). Refer to [TikTok Shop Restricted Products Policy](https://seller-us.tiktok.com/university/essay?identity=1&role=1&knowledge_id=3238037484275457&from=policy) for information on product category restrictions.
    Certifications []Product202309EditGlobalProductRequestBodyCertifications `json:"certifications,omitempty"`
    // The product description in HTML format.  **Note**: - The content must conform to the [HTML syntax](https://html.spec.whatwg.org/). All HTML tags are accepted but to optimize display on the TikTok Shop product detail page, the system will automatically convert certain tags into alternative formats, such as rendering `<table>` tags as images. - Max length: 10,000 characters. - Image guidelines: You must use [TikTok Shop image URLs](6509df95defece02be598a22). Max 30 `<img>` tags, each under 4000px with `src`, `width`, and `height` attributes.  **Recommendations**:  - If you are syncing a pre-existing description from another platform, include the full HTML source description here. - Provide a detailed description, ideally over 300 characters. - Include 3-5 key selling points, each under 250 characters, with supporting images. - Use 1600x1600 px for the image dimensions.
    Description *string `json:"description,omitempty"`
    // An external identifier used in an external ecommerce platform. This is used to associate the global product between TikTok Shop and the external ecommerce platform.  Max length: 999 characters
    ExternalGlobalProductId *string `json:"external_global_product_id,omitempty"`
    // A list of images to display in the product image gallery. - Max count: 9 - Arrange your image URIs in the sequence that they should appear on TikTok Shop. - Image dimensions: [300x300 px, 4000x4000 px]    **Recommendations**: - Use a minimum of 5 images. - The first image should have a white background. Use the [Optimize Images API](https://partner.tiktokshop.com/docv2/page/665692b35d39dc02deb49a97) to change the background to white.
    MainImages []Product202309EditGlobalProductRequestBodyMainImages `json:"main_images,omitempty"`
    Manufacturer *Product202309EditGlobalProductRequestBodyManufacturer `json:"manufacturer,omitempty"`
    // A comma-delimited list of manufacturer IDs. Retrieve the IDs from the [Search Manufacturers API](67066a580dcee902fa03ccf9). Default: The IDs provided when the global product was created.  **Note**: Applicable only for the EU market in certain categories. Use the [Get Global Category Rules API](650a056df1fd3102b91b5b8e) to check the requirements.
    ManufacturerIds []string `json:"manufacturer_ids,omitempty"`
    PackageDimensions *Product202309EditGlobalProductRequestBodyPackageDimensions `json:"package_dimensions,omitempty"`
    PackageWeight *Product202309EditGlobalProductRequestBodyPackageWeight `json:"package_weight,omitempty"`
    // A list of general attributes (e.g. manufacturer, country of origin, materials used) that describe the product as a whole, regardless of variant.  **Important**: The attributes available for use are determined by the system based on the product's assigned category, with some being mandatory. You must provide the product attributes marked as `is_required` in the response of the [Get Global Attributes API](650a0483c16ffe02b8dfc80a).
    ProductAttributes []Product202309EditGlobalProductRequestBodyProductAttributes `json:"product_attributes,omitempty"`
    // A comma-delimited list of responsible person IDs. Retrieve the IDs from the [Search Responsible Persons API](67066a55f17b7d02f95d2fb1). Default: The IDs provided when the global product was created.  **Note**: Applicable only for the EU market in certain categories. Use the [Get Global Category Rules API](650a056df1fd3102b91b5b8e) to check the requirements.
    ResponsiblePersonIds []string `json:"responsible_person_ids,omitempty"`
    SizeChart *Product202309EditGlobalProductRequestBodySizeChart `json:"size_chart,omitempty"`
    // A list of global Stock Keeping Units (SKUs) used to identify distinct variants of the product.  **Note**: - Max SKUs for EU, JP, UK, US: 300 - Max SKUs for other regions: 100  **Recommendations**: Place the most important variant at the beginning of the array.
    Skus []Product202309EditGlobalProductRequestBodySkus `json:"skus,omitempty"`
    // The product title.  Title length: - DE, ES, FR, IE, IT, JP, UK, US: [1, 255]  - MX:[1,300]  - Other regions: [25, 255]
    Title *string `json:"title,omitempty"`
    Video *Product202309EditGlobalProductRequestBodyVideo `json:"video,omitempty"`
}

// NewProduct202309EditGlobalProductRequestBody instantiates a new Product202309EditGlobalProductRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202309EditGlobalProductRequestBody() *Product202309EditGlobalProductRequestBody {
    this := Product202309EditGlobalProductRequestBody{}
    return &this
}

// NewProduct202309EditGlobalProductRequestBodyWithDefaults instantiates a new Product202309EditGlobalProductRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202309EditGlobalProductRequestBodyWithDefaults() *Product202309EditGlobalProductRequestBody {
    this := Product202309EditGlobalProductRequestBody{}
    return &this
}

// GetBrandId returns the BrandId field value if set, zero value otherwise.
func (o *Product202309EditGlobalProductRequestBody) GetBrandId() string {
    if o == nil || utils.IsNil(o.BrandId) {
        var ret string
        return ret
    }
    return *o.BrandId
}

// GetBrandIdOk returns a tuple with the BrandId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditGlobalProductRequestBody) GetBrandIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.BrandId) {
        return nil, false
    }
    return o.BrandId, true
}

// HasBrandId returns a boolean if a field has been set.
func (o *Product202309EditGlobalProductRequestBody) HasBrandId() bool {
    if o != nil && !utils.IsNil(o.BrandId) {
        return true
    }

    return false
}

// SetBrandId gets a reference to the given string and assigns it to the BrandId field.
func (o *Product202309EditGlobalProductRequestBody) SetBrandId(v string) {
    o.BrandId = &v
}

// GetCategoryId returns the CategoryId field value if set, zero value otherwise.
func (o *Product202309EditGlobalProductRequestBody) GetCategoryId() string {
    if o == nil || utils.IsNil(o.CategoryId) {
        var ret string
        return ret
    }
    return *o.CategoryId
}

// GetCategoryIdOk returns a tuple with the CategoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditGlobalProductRequestBody) GetCategoryIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.CategoryId) {
        return nil, false
    }
    return o.CategoryId, true
}

// HasCategoryId returns a boolean if a field has been set.
func (o *Product202309EditGlobalProductRequestBody) HasCategoryId() bool {
    if o != nil && !utils.IsNil(o.CategoryId) {
        return true
    }

    return false
}

// SetCategoryId gets a reference to the given string and assigns it to the CategoryId field.
func (o *Product202309EditGlobalProductRequestBody) SetCategoryId(v string) {
    o.CategoryId = &v
}

// GetCategoryVersion returns the CategoryVersion field value if set, zero value otherwise.
func (o *Product202309EditGlobalProductRequestBody) GetCategoryVersion() string {
    if o == nil || utils.IsNil(o.CategoryVersion) {
        var ret string
        return ret
    }
    return *o.CategoryVersion
}

// GetCategoryVersionOk returns a tuple with the CategoryVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditGlobalProductRequestBody) GetCategoryVersionOk() (*string, bool) {
    if o == nil || utils.IsNil(o.CategoryVersion) {
        return nil, false
    }
    return o.CategoryVersion, true
}

// HasCategoryVersion returns a boolean if a field has been set.
func (o *Product202309EditGlobalProductRequestBody) HasCategoryVersion() bool {
    if o != nil && !utils.IsNil(o.CategoryVersion) {
        return true
    }

    return false
}

// SetCategoryVersion gets a reference to the given string and assigns it to the CategoryVersion field.
func (o *Product202309EditGlobalProductRequestBody) SetCategoryVersion(v string) {
    o.CategoryVersion = &v
}

// GetCertifications returns the Certifications field value if set, zero value otherwise.
func (o *Product202309EditGlobalProductRequestBody) GetCertifications() []Product202309EditGlobalProductRequestBodyCertifications {
    if o == nil || utils.IsNil(o.Certifications) {
        var ret []Product202309EditGlobalProductRequestBodyCertifications
        return ret
    }
    return o.Certifications
}

// GetCertificationsOk returns a tuple with the Certifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditGlobalProductRequestBody) GetCertificationsOk() ([]Product202309EditGlobalProductRequestBodyCertifications, bool) {
    if o == nil || utils.IsNil(o.Certifications) {
        return nil, false
    }
    return o.Certifications, true
}

// HasCertifications returns a boolean if a field has been set.
func (o *Product202309EditGlobalProductRequestBody) HasCertifications() bool {
    if o != nil && !utils.IsNil(o.Certifications) {
        return true
    }

    return false
}

// SetCertifications gets a reference to the given []Product202309EditGlobalProductRequestBodyCertifications and assigns it to the Certifications field.
func (o *Product202309EditGlobalProductRequestBody) SetCertifications(v []Product202309EditGlobalProductRequestBodyCertifications) {
    o.Certifications = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Product202309EditGlobalProductRequestBody) GetDescription() string {
    if o == nil || utils.IsNil(o.Description) {
        var ret string
        return ret
    }
    return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditGlobalProductRequestBody) GetDescriptionOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Description) {
        return nil, false
    }
    return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Product202309EditGlobalProductRequestBody) HasDescription() bool {
    if o != nil && !utils.IsNil(o.Description) {
        return true
    }

    return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Product202309EditGlobalProductRequestBody) SetDescription(v string) {
    o.Description = &v
}

// GetExternalGlobalProductId returns the ExternalGlobalProductId field value if set, zero value otherwise.
func (o *Product202309EditGlobalProductRequestBody) GetExternalGlobalProductId() string {
    if o == nil || utils.IsNil(o.ExternalGlobalProductId) {
        var ret string
        return ret
    }
    return *o.ExternalGlobalProductId
}

// GetExternalGlobalProductIdOk returns a tuple with the ExternalGlobalProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditGlobalProductRequestBody) GetExternalGlobalProductIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.ExternalGlobalProductId) {
        return nil, false
    }
    return o.ExternalGlobalProductId, true
}

// HasExternalGlobalProductId returns a boolean if a field has been set.
func (o *Product202309EditGlobalProductRequestBody) HasExternalGlobalProductId() bool {
    if o != nil && !utils.IsNil(o.ExternalGlobalProductId) {
        return true
    }

    return false
}

// SetExternalGlobalProductId gets a reference to the given string and assigns it to the ExternalGlobalProductId field.
func (o *Product202309EditGlobalProductRequestBody) SetExternalGlobalProductId(v string) {
    o.ExternalGlobalProductId = &v
}

// GetMainImages returns the MainImages field value if set, zero value otherwise.
func (o *Product202309EditGlobalProductRequestBody) GetMainImages() []Product202309EditGlobalProductRequestBodyMainImages {
    if o == nil || utils.IsNil(o.MainImages) {
        var ret []Product202309EditGlobalProductRequestBodyMainImages
        return ret
    }
    return o.MainImages
}

// GetMainImagesOk returns a tuple with the MainImages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditGlobalProductRequestBody) GetMainImagesOk() ([]Product202309EditGlobalProductRequestBodyMainImages, bool) {
    if o == nil || utils.IsNil(o.MainImages) {
        return nil, false
    }
    return o.MainImages, true
}

// HasMainImages returns a boolean if a field has been set.
func (o *Product202309EditGlobalProductRequestBody) HasMainImages() bool {
    if o != nil && !utils.IsNil(o.MainImages) {
        return true
    }

    return false
}

// SetMainImages gets a reference to the given []Product202309EditGlobalProductRequestBodyMainImages and assigns it to the MainImages field.
func (o *Product202309EditGlobalProductRequestBody) SetMainImages(v []Product202309EditGlobalProductRequestBodyMainImages) {
    o.MainImages = v
}

// GetManufacturer returns the Manufacturer field value if set, zero value otherwise.
func (o *Product202309EditGlobalProductRequestBody) GetManufacturer() Product202309EditGlobalProductRequestBodyManufacturer {
    if o == nil || utils.IsNil(o.Manufacturer) {
        var ret Product202309EditGlobalProductRequestBodyManufacturer
        return ret
    }
    return *o.Manufacturer
}

// GetManufacturerOk returns a tuple with the Manufacturer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditGlobalProductRequestBody) GetManufacturerOk() (*Product202309EditGlobalProductRequestBodyManufacturer, bool) {
    if o == nil || utils.IsNil(o.Manufacturer) {
        return nil, false
    }
    return o.Manufacturer, true
}

// HasManufacturer returns a boolean if a field has been set.
func (o *Product202309EditGlobalProductRequestBody) HasManufacturer() bool {
    if o != nil && !utils.IsNil(o.Manufacturer) {
        return true
    }

    return false
}

// SetManufacturer gets a reference to the given Product202309EditGlobalProductRequestBodyManufacturer and assigns it to the Manufacturer field.
func (o *Product202309EditGlobalProductRequestBody) SetManufacturer(v Product202309EditGlobalProductRequestBodyManufacturer) {
    o.Manufacturer = &v
}

// GetManufacturerIds returns the ManufacturerIds field value if set, zero value otherwise.
func (o *Product202309EditGlobalProductRequestBody) GetManufacturerIds() []string {
    if o == nil || utils.IsNil(o.ManufacturerIds) {
        var ret []string
        return ret
    }
    return o.ManufacturerIds
}

// GetManufacturerIdsOk returns a tuple with the ManufacturerIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditGlobalProductRequestBody) GetManufacturerIdsOk() ([]string, bool) {
    if o == nil || utils.IsNil(o.ManufacturerIds) {
        return nil, false
    }
    return o.ManufacturerIds, true
}

// HasManufacturerIds returns a boolean if a field has been set.
func (o *Product202309EditGlobalProductRequestBody) HasManufacturerIds() bool {
    if o != nil && !utils.IsNil(o.ManufacturerIds) {
        return true
    }

    return false
}

// SetManufacturerIds gets a reference to the given []string and assigns it to the ManufacturerIds field.
func (o *Product202309EditGlobalProductRequestBody) SetManufacturerIds(v []string) {
    o.ManufacturerIds = v
}

// GetPackageDimensions returns the PackageDimensions field value if set, zero value otherwise.
func (o *Product202309EditGlobalProductRequestBody) GetPackageDimensions() Product202309EditGlobalProductRequestBodyPackageDimensions {
    if o == nil || utils.IsNil(o.PackageDimensions) {
        var ret Product202309EditGlobalProductRequestBodyPackageDimensions
        return ret
    }
    return *o.PackageDimensions
}

// GetPackageDimensionsOk returns a tuple with the PackageDimensions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditGlobalProductRequestBody) GetPackageDimensionsOk() (*Product202309EditGlobalProductRequestBodyPackageDimensions, bool) {
    if o == nil || utils.IsNil(o.PackageDimensions) {
        return nil, false
    }
    return o.PackageDimensions, true
}

// HasPackageDimensions returns a boolean if a field has been set.
func (o *Product202309EditGlobalProductRequestBody) HasPackageDimensions() bool {
    if o != nil && !utils.IsNil(o.PackageDimensions) {
        return true
    }

    return false
}

// SetPackageDimensions gets a reference to the given Product202309EditGlobalProductRequestBodyPackageDimensions and assigns it to the PackageDimensions field.
func (o *Product202309EditGlobalProductRequestBody) SetPackageDimensions(v Product202309EditGlobalProductRequestBodyPackageDimensions) {
    o.PackageDimensions = &v
}

// GetPackageWeight returns the PackageWeight field value if set, zero value otherwise.
func (o *Product202309EditGlobalProductRequestBody) GetPackageWeight() Product202309EditGlobalProductRequestBodyPackageWeight {
    if o == nil || utils.IsNil(o.PackageWeight) {
        var ret Product202309EditGlobalProductRequestBodyPackageWeight
        return ret
    }
    return *o.PackageWeight
}

// GetPackageWeightOk returns a tuple with the PackageWeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditGlobalProductRequestBody) GetPackageWeightOk() (*Product202309EditGlobalProductRequestBodyPackageWeight, bool) {
    if o == nil || utils.IsNil(o.PackageWeight) {
        return nil, false
    }
    return o.PackageWeight, true
}

// HasPackageWeight returns a boolean if a field has been set.
func (o *Product202309EditGlobalProductRequestBody) HasPackageWeight() bool {
    if o != nil && !utils.IsNil(o.PackageWeight) {
        return true
    }

    return false
}

// SetPackageWeight gets a reference to the given Product202309EditGlobalProductRequestBodyPackageWeight and assigns it to the PackageWeight field.
func (o *Product202309EditGlobalProductRequestBody) SetPackageWeight(v Product202309EditGlobalProductRequestBodyPackageWeight) {
    o.PackageWeight = &v
}

// GetProductAttributes returns the ProductAttributes field value if set, zero value otherwise.
func (o *Product202309EditGlobalProductRequestBody) GetProductAttributes() []Product202309EditGlobalProductRequestBodyProductAttributes {
    if o == nil || utils.IsNil(o.ProductAttributes) {
        var ret []Product202309EditGlobalProductRequestBodyProductAttributes
        return ret
    }
    return o.ProductAttributes
}

// GetProductAttributesOk returns a tuple with the ProductAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditGlobalProductRequestBody) GetProductAttributesOk() ([]Product202309EditGlobalProductRequestBodyProductAttributes, bool) {
    if o == nil || utils.IsNil(o.ProductAttributes) {
        return nil, false
    }
    return o.ProductAttributes, true
}

// HasProductAttributes returns a boolean if a field has been set.
func (o *Product202309EditGlobalProductRequestBody) HasProductAttributes() bool {
    if o != nil && !utils.IsNil(o.ProductAttributes) {
        return true
    }

    return false
}

// SetProductAttributes gets a reference to the given []Product202309EditGlobalProductRequestBodyProductAttributes and assigns it to the ProductAttributes field.
func (o *Product202309EditGlobalProductRequestBody) SetProductAttributes(v []Product202309EditGlobalProductRequestBodyProductAttributes) {
    o.ProductAttributes = v
}

// GetResponsiblePersonIds returns the ResponsiblePersonIds field value if set, zero value otherwise.
func (o *Product202309EditGlobalProductRequestBody) GetResponsiblePersonIds() []string {
    if o == nil || utils.IsNil(o.ResponsiblePersonIds) {
        var ret []string
        return ret
    }
    return o.ResponsiblePersonIds
}

// GetResponsiblePersonIdsOk returns a tuple with the ResponsiblePersonIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditGlobalProductRequestBody) GetResponsiblePersonIdsOk() ([]string, bool) {
    if o == nil || utils.IsNil(o.ResponsiblePersonIds) {
        return nil, false
    }
    return o.ResponsiblePersonIds, true
}

// HasResponsiblePersonIds returns a boolean if a field has been set.
func (o *Product202309EditGlobalProductRequestBody) HasResponsiblePersonIds() bool {
    if o != nil && !utils.IsNil(o.ResponsiblePersonIds) {
        return true
    }

    return false
}

// SetResponsiblePersonIds gets a reference to the given []string and assigns it to the ResponsiblePersonIds field.
func (o *Product202309EditGlobalProductRequestBody) SetResponsiblePersonIds(v []string) {
    o.ResponsiblePersonIds = v
}

// GetSizeChart returns the SizeChart field value if set, zero value otherwise.
func (o *Product202309EditGlobalProductRequestBody) GetSizeChart() Product202309EditGlobalProductRequestBodySizeChart {
    if o == nil || utils.IsNil(o.SizeChart) {
        var ret Product202309EditGlobalProductRequestBodySizeChart
        return ret
    }
    return *o.SizeChart
}

// GetSizeChartOk returns a tuple with the SizeChart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditGlobalProductRequestBody) GetSizeChartOk() (*Product202309EditGlobalProductRequestBodySizeChart, bool) {
    if o == nil || utils.IsNil(o.SizeChart) {
        return nil, false
    }
    return o.SizeChart, true
}

// HasSizeChart returns a boolean if a field has been set.
func (o *Product202309EditGlobalProductRequestBody) HasSizeChart() bool {
    if o != nil && !utils.IsNil(o.SizeChart) {
        return true
    }

    return false
}

// SetSizeChart gets a reference to the given Product202309EditGlobalProductRequestBodySizeChart and assigns it to the SizeChart field.
func (o *Product202309EditGlobalProductRequestBody) SetSizeChart(v Product202309EditGlobalProductRequestBodySizeChart) {
    o.SizeChart = &v
}

// GetSkus returns the Skus field value if set, zero value otherwise.
func (o *Product202309EditGlobalProductRequestBody) GetSkus() []Product202309EditGlobalProductRequestBodySkus {
    if o == nil || utils.IsNil(o.Skus) {
        var ret []Product202309EditGlobalProductRequestBodySkus
        return ret
    }
    return o.Skus
}

// GetSkusOk returns a tuple with the Skus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditGlobalProductRequestBody) GetSkusOk() ([]Product202309EditGlobalProductRequestBodySkus, bool) {
    if o == nil || utils.IsNil(o.Skus) {
        return nil, false
    }
    return o.Skus, true
}

// HasSkus returns a boolean if a field has been set.
func (o *Product202309EditGlobalProductRequestBody) HasSkus() bool {
    if o != nil && !utils.IsNil(o.Skus) {
        return true
    }

    return false
}

// SetSkus gets a reference to the given []Product202309EditGlobalProductRequestBodySkus and assigns it to the Skus field.
func (o *Product202309EditGlobalProductRequestBody) SetSkus(v []Product202309EditGlobalProductRequestBodySkus) {
    o.Skus = v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *Product202309EditGlobalProductRequestBody) GetTitle() string {
    if o == nil || utils.IsNil(o.Title) {
        var ret string
        return ret
    }
    return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditGlobalProductRequestBody) GetTitleOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Title) {
        return nil, false
    }
    return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *Product202309EditGlobalProductRequestBody) HasTitle() bool {
    if o != nil && !utils.IsNil(o.Title) {
        return true
    }

    return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *Product202309EditGlobalProductRequestBody) SetTitle(v string) {
    o.Title = &v
}

// GetVideo returns the Video field value if set, zero value otherwise.
func (o *Product202309EditGlobalProductRequestBody) GetVideo() Product202309EditGlobalProductRequestBodyVideo {
    if o == nil || utils.IsNil(o.Video) {
        var ret Product202309EditGlobalProductRequestBodyVideo
        return ret
    }
    return *o.Video
}

// GetVideoOk returns a tuple with the Video field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309EditGlobalProductRequestBody) GetVideoOk() (*Product202309EditGlobalProductRequestBodyVideo, bool) {
    if o == nil || utils.IsNil(o.Video) {
        return nil, false
    }
    return o.Video, true
}

// HasVideo returns a boolean if a field has been set.
func (o *Product202309EditGlobalProductRequestBody) HasVideo() bool {
    if o != nil && !utils.IsNil(o.Video) {
        return true
    }

    return false
}

// SetVideo gets a reference to the given Product202309EditGlobalProductRequestBodyVideo and assigns it to the Video field.
func (o *Product202309EditGlobalProductRequestBody) SetVideo(v Product202309EditGlobalProductRequestBodyVideo) {
    o.Video = &v
}

func (o Product202309EditGlobalProductRequestBody) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202309EditGlobalProductRequestBody) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.BrandId) {
        toSerialize["brand_id"] = o.BrandId
    }
    if !utils.IsNil(o.CategoryId) {
        toSerialize["category_id"] = o.CategoryId
    }
    if !utils.IsNil(o.CategoryVersion) {
        toSerialize["category_version"] = o.CategoryVersion
    }
    if !utils.IsNil(o.Certifications) {
        toSerialize["certifications"] = o.Certifications
    }
    if !utils.IsNil(o.Description) {
        toSerialize["description"] = o.Description
    }
    if !utils.IsNil(o.ExternalGlobalProductId) {
        toSerialize["external_global_product_id"] = o.ExternalGlobalProductId
    }
    if !utils.IsNil(o.MainImages) {
        toSerialize["main_images"] = o.MainImages
    }
    if !utils.IsNil(o.Manufacturer) {
        toSerialize["manufacturer"] = o.Manufacturer
    }
    if !utils.IsNil(o.ManufacturerIds) {
        toSerialize["manufacturer_ids"] = o.ManufacturerIds
    }
    if !utils.IsNil(o.PackageDimensions) {
        toSerialize["package_dimensions"] = o.PackageDimensions
    }
    if !utils.IsNil(o.PackageWeight) {
        toSerialize["package_weight"] = o.PackageWeight
    }
    if !utils.IsNil(o.ProductAttributes) {
        toSerialize["product_attributes"] = o.ProductAttributes
    }
    if !utils.IsNil(o.ResponsiblePersonIds) {
        toSerialize["responsible_person_ids"] = o.ResponsiblePersonIds
    }
    if !utils.IsNil(o.SizeChart) {
        toSerialize["size_chart"] = o.SizeChart
    }
    if !utils.IsNil(o.Skus) {
        toSerialize["skus"] = o.Skus
    }
    if !utils.IsNil(o.Title) {
        toSerialize["title"] = o.Title
    }
    if !utils.IsNil(o.Video) {
        toSerialize["video"] = o.Video
    }
    return toSerialize, nil
}

type NullableProduct202309EditGlobalProductRequestBody struct {
	value *Product202309EditGlobalProductRequestBody
	isSet bool
}

func (v NullableProduct202309EditGlobalProductRequestBody) Get() *Product202309EditGlobalProductRequestBody {
	return v.value
}

func (v *NullableProduct202309EditGlobalProductRequestBody) Set(val *Product202309EditGlobalProductRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202309EditGlobalProductRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202309EditGlobalProductRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202309EditGlobalProductRequestBody(val *Product202309EditGlobalProductRequestBody) *NullableProduct202309EditGlobalProductRequestBody {
	return &NullableProduct202309EditGlobalProductRequestBody{value: val, isSet: true}
}

func (v NullableProduct202309EditGlobalProductRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202309EditGlobalProductRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


