/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202309GetGlobalProductResponseDataSkusInventory type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202309GetGlobalProductResponseDataSkusInventory{}

// Product202309GetGlobalProductResponseDataSkusInventory struct for Product202309GetGlobalProductResponseDataSkusInventory
type Product202309GetGlobalProductResponseDataSkusInventory struct {
    // The ID of the global warehouse where the SKU is stored. 
    GlobalWarehouseId *string `json:"global_warehouse_id,omitempty"`
    // The SKU quantity available in the warehouse.
    Quantity *int32 `json:"quantity,omitempty"`
}

// NewProduct202309GetGlobalProductResponseDataSkusInventory instantiates a new Product202309GetGlobalProductResponseDataSkusInventory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202309GetGlobalProductResponseDataSkusInventory() *Product202309GetGlobalProductResponseDataSkusInventory {
    this := Product202309GetGlobalProductResponseDataSkusInventory{}
    return &this
}

// NewProduct202309GetGlobalProductResponseDataSkusInventoryWithDefaults instantiates a new Product202309GetGlobalProductResponseDataSkusInventory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202309GetGlobalProductResponseDataSkusInventoryWithDefaults() *Product202309GetGlobalProductResponseDataSkusInventory {
    this := Product202309GetGlobalProductResponseDataSkusInventory{}
    return &this
}

// GetGlobalWarehouseId returns the GlobalWarehouseId field value if set, zero value otherwise.
func (o *Product202309GetGlobalProductResponseDataSkusInventory) GetGlobalWarehouseId() string {
    if o == nil || utils.IsNil(o.GlobalWarehouseId) {
        var ret string
        return ret
    }
    return *o.GlobalWarehouseId
}

// GetGlobalWarehouseIdOk returns a tuple with the GlobalWarehouseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309GetGlobalProductResponseDataSkusInventory) GetGlobalWarehouseIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.GlobalWarehouseId) {
        return nil, false
    }
    return o.GlobalWarehouseId, true
}

// HasGlobalWarehouseId returns a boolean if a field has been set.
func (o *Product202309GetGlobalProductResponseDataSkusInventory) HasGlobalWarehouseId() bool {
    if o != nil && !utils.IsNil(o.GlobalWarehouseId) {
        return true
    }

    return false
}

// SetGlobalWarehouseId gets a reference to the given string and assigns it to the GlobalWarehouseId field.
func (o *Product202309GetGlobalProductResponseDataSkusInventory) SetGlobalWarehouseId(v string) {
    o.GlobalWarehouseId = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *Product202309GetGlobalProductResponseDataSkusInventory) GetQuantity() int32 {
    if o == nil || utils.IsNil(o.Quantity) {
        var ret int32
        return ret
    }
    return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309GetGlobalProductResponseDataSkusInventory) GetQuantityOk() (*int32, bool) {
    if o == nil || utils.IsNil(o.Quantity) {
        return nil, false
    }
    return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *Product202309GetGlobalProductResponseDataSkusInventory) HasQuantity() bool {
    if o != nil && !utils.IsNil(o.Quantity) {
        return true
    }

    return false
}

// SetQuantity gets a reference to the given int32 and assigns it to the Quantity field.
func (o *Product202309GetGlobalProductResponseDataSkusInventory) SetQuantity(v int32) {
    o.Quantity = &v
}

func (o Product202309GetGlobalProductResponseDataSkusInventory) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202309GetGlobalProductResponseDataSkusInventory) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.GlobalWarehouseId) {
        toSerialize["global_warehouse_id"] = o.GlobalWarehouseId
    }
    if !utils.IsNil(o.Quantity) {
        toSerialize["quantity"] = o.Quantity
    }
    return toSerialize, nil
}

type NullableProduct202309GetGlobalProductResponseDataSkusInventory struct {
	value *Product202309GetGlobalProductResponseDataSkusInventory
	isSet bool
}

func (v NullableProduct202309GetGlobalProductResponseDataSkusInventory) Get() *Product202309GetGlobalProductResponseDataSkusInventory {
	return v.value
}

func (v *NullableProduct202309GetGlobalProductResponseDataSkusInventory) Set(val *Product202309GetGlobalProductResponseDataSkusInventory) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202309GetGlobalProductResponseDataSkusInventory) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202309GetGlobalProductResponseDataSkusInventory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202309GetGlobalProductResponseDataSkusInventory(val *Product202309GetGlobalProductResponseDataSkusInventory) *NullableProduct202309GetGlobalProductResponseDataSkusInventory {
	return &NullableProduct202309GetGlobalProductResponseDataSkusInventory{value: val, isSet: true}
}

func (v NullableProduct202309GetGlobalProductResponseDataSkusInventory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202309GetGlobalProductResponseDataSkusInventory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


