/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202309GetGlobalProductResponseDataCertificationsFiles type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202309GetGlobalProductResponseDataCertificationsFiles{}

// Product202309GetGlobalProductResponseDataCertificationsFiles struct for Product202309GetGlobalProductResponseDataCertificationsFiles
type Product202309GetGlobalProductResponseDataCertificationsFiles struct {
    // The format of the certification file.
    Format *string `json:"format,omitempty"`
    // The ID of the certification file.
    Id *string `json:"id,omitempty"`
    // The name of the certification file
    Name *string `json:"name,omitempty"`
    //  The URLs to view the certification files. 
    Urls []string `json:"urls,omitempty"`
}

// NewProduct202309GetGlobalProductResponseDataCertificationsFiles instantiates a new Product202309GetGlobalProductResponseDataCertificationsFiles object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202309GetGlobalProductResponseDataCertificationsFiles() *Product202309GetGlobalProductResponseDataCertificationsFiles {
    this := Product202309GetGlobalProductResponseDataCertificationsFiles{}
    return &this
}

// NewProduct202309GetGlobalProductResponseDataCertificationsFilesWithDefaults instantiates a new Product202309GetGlobalProductResponseDataCertificationsFiles object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202309GetGlobalProductResponseDataCertificationsFilesWithDefaults() *Product202309GetGlobalProductResponseDataCertificationsFiles {
    this := Product202309GetGlobalProductResponseDataCertificationsFiles{}
    return &this
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *Product202309GetGlobalProductResponseDataCertificationsFiles) GetFormat() string {
    if o == nil || utils.IsNil(o.Format) {
        var ret string
        return ret
    }
    return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309GetGlobalProductResponseDataCertificationsFiles) GetFormatOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Format) {
        return nil, false
    }
    return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *Product202309GetGlobalProductResponseDataCertificationsFiles) HasFormat() bool {
    if o != nil && !utils.IsNil(o.Format) {
        return true
    }

    return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *Product202309GetGlobalProductResponseDataCertificationsFiles) SetFormat(v string) {
    o.Format = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Product202309GetGlobalProductResponseDataCertificationsFiles) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309GetGlobalProductResponseDataCertificationsFiles) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Product202309GetGlobalProductResponseDataCertificationsFiles) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Product202309GetGlobalProductResponseDataCertificationsFiles) SetId(v string) {
    o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Product202309GetGlobalProductResponseDataCertificationsFiles) GetName() string {
    if o == nil || utils.IsNil(o.Name) {
        var ret string
        return ret
    }
    return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309GetGlobalProductResponseDataCertificationsFiles) GetNameOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Name) {
        return nil, false
    }
    return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Product202309GetGlobalProductResponseDataCertificationsFiles) HasName() bool {
    if o != nil && !utils.IsNil(o.Name) {
        return true
    }

    return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Product202309GetGlobalProductResponseDataCertificationsFiles) SetName(v string) {
    o.Name = &v
}

// GetUrls returns the Urls field value if set, zero value otherwise.
func (o *Product202309GetGlobalProductResponseDataCertificationsFiles) GetUrls() []string {
    if o == nil || utils.IsNil(o.Urls) {
        var ret []string
        return ret
    }
    return o.Urls
}

// GetUrlsOk returns a tuple with the Urls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309GetGlobalProductResponseDataCertificationsFiles) GetUrlsOk() ([]string, bool) {
    if o == nil || utils.IsNil(o.Urls) {
        return nil, false
    }
    return o.Urls, true
}

// HasUrls returns a boolean if a field has been set.
func (o *Product202309GetGlobalProductResponseDataCertificationsFiles) HasUrls() bool {
    if o != nil && !utils.IsNil(o.Urls) {
        return true
    }

    return false
}

// SetUrls gets a reference to the given []string and assigns it to the Urls field.
func (o *Product202309GetGlobalProductResponseDataCertificationsFiles) SetUrls(v []string) {
    o.Urls = v
}

func (o Product202309GetGlobalProductResponseDataCertificationsFiles) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202309GetGlobalProductResponseDataCertificationsFiles) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Format) {
        toSerialize["format"] = o.Format
    }
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }
    if !utils.IsNil(o.Name) {
        toSerialize["name"] = o.Name
    }
    if !utils.IsNil(o.Urls) {
        toSerialize["urls"] = o.Urls
    }
    return toSerialize, nil
}

type NullableProduct202309GetGlobalProductResponseDataCertificationsFiles struct {
	value *Product202309GetGlobalProductResponseDataCertificationsFiles
	isSet bool
}

func (v NullableProduct202309GetGlobalProductResponseDataCertificationsFiles) Get() *Product202309GetGlobalProductResponseDataCertificationsFiles {
	return v.value
}

func (v *NullableProduct202309GetGlobalProductResponseDataCertificationsFiles) Set(val *Product202309GetGlobalProductResponseDataCertificationsFiles) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202309GetGlobalProductResponseDataCertificationsFiles) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202309GetGlobalProductResponseDataCertificationsFiles) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202309GetGlobalProductResponseDataCertificationsFiles(val *Product202309GetGlobalProductResponseDataCertificationsFiles) *NullableProduct202309GetGlobalProductResponseDataCertificationsFiles {
	return &NullableProduct202309GetGlobalProductResponseDataCertificationsFiles{value: val, isSet: true}
}

func (v NullableProduct202309GetGlobalProductResponseDataCertificationsFiles) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202309GetGlobalProductResponseDataCertificationsFiles) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


