/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202309PartialEditProductRequestBodySizeChartImage type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202309PartialEditProductRequestBodySizeChartImage{}

// Product202309PartialEditProductRequestBodySizeChartImage struct for Product202309PartialEditProductRequestBodySizeChartImage
type Product202309PartialEditProductRequestBodySizeChartImage struct {
    // The URI of the size chart image. Obtain this URI by uploading the images through the [Upload Product Image API](6509df95defece02be598a22)  with `use_case=SIZE_CHART_IMAGE`. 
    Uri *string `json:"uri,omitempty"`
}

// NewProduct202309PartialEditProductRequestBodySizeChartImage instantiates a new Product202309PartialEditProductRequestBodySizeChartImage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202309PartialEditProductRequestBodySizeChartImage() *Product202309PartialEditProductRequestBodySizeChartImage {
    this := Product202309PartialEditProductRequestBodySizeChartImage{}
    return &this
}

// NewProduct202309PartialEditProductRequestBodySizeChartImageWithDefaults instantiates a new Product202309PartialEditProductRequestBodySizeChartImage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202309PartialEditProductRequestBodySizeChartImageWithDefaults() *Product202309PartialEditProductRequestBodySizeChartImage {
    this := Product202309PartialEditProductRequestBodySizeChartImage{}
    return &this
}

// GetUri returns the Uri field value if set, zero value otherwise.
func (o *Product202309PartialEditProductRequestBodySizeChartImage) GetUri() string {
    if o == nil || utils.IsNil(o.Uri) {
        var ret string
        return ret
    }
    return *o.Uri
}

// GetUriOk returns a tuple with the Uri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309PartialEditProductRequestBodySizeChartImage) GetUriOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Uri) {
        return nil, false
    }
    return o.Uri, true
}

// HasUri returns a boolean if a field has been set.
func (o *Product202309PartialEditProductRequestBodySizeChartImage) HasUri() bool {
    if o != nil && !utils.IsNil(o.Uri) {
        return true
    }

    return false
}

// SetUri gets a reference to the given string and assigns it to the Uri field.
func (o *Product202309PartialEditProductRequestBodySizeChartImage) SetUri(v string) {
    o.Uri = &v
}

func (o Product202309PartialEditProductRequestBodySizeChartImage) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202309PartialEditProductRequestBodySizeChartImage) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Uri) {
        toSerialize["uri"] = o.Uri
    }
    return toSerialize, nil
}

type NullableProduct202309PartialEditProductRequestBodySizeChartImage struct {
	value *Product202309PartialEditProductRequestBodySizeChartImage
	isSet bool
}

func (v NullableProduct202309PartialEditProductRequestBodySizeChartImage) Get() *Product202309PartialEditProductRequestBodySizeChartImage {
	return v.value
}

func (v *NullableProduct202309PartialEditProductRequestBodySizeChartImage) Set(val *Product202309PartialEditProductRequestBodySizeChartImage) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202309PartialEditProductRequestBodySizeChartImage) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202309PartialEditProductRequestBodySizeChartImage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202309PartialEditProductRequestBodySizeChartImage(val *Product202309PartialEditProductRequestBodySizeChartImage) *NullableProduct202309PartialEditProductRequestBodySizeChartImage {
	return &NullableProduct202309PartialEditProductRequestBodySizeChartImage{value: val, isSet: true}
}

func (v NullableProduct202309PartialEditProductRequestBodySizeChartImage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202309PartialEditProductRequestBodySizeChartImage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


