/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202309PartialEditProductRequestBodySizeChart type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202309PartialEditProductRequestBodySizeChart{}

// Product202309PartialEditProductRequestBodySizeChart struct for Product202309PartialEditProductRequestBodySizeChart
type Product202309PartialEditProductRequestBodySizeChart struct {
    Image *Product202309PartialEditProductRequestBodySizeChartImage `json:"image,omitempty"`
    Template *Product202309PartialEditProductRequestBodySizeChartTemplate `json:"template,omitempty"`
}

// NewProduct202309PartialEditProductRequestBodySizeChart instantiates a new Product202309PartialEditProductRequestBodySizeChart object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202309PartialEditProductRequestBodySizeChart() *Product202309PartialEditProductRequestBodySizeChart {
    this := Product202309PartialEditProductRequestBodySizeChart{}
    return &this
}

// NewProduct202309PartialEditProductRequestBodySizeChartWithDefaults instantiates a new Product202309PartialEditProductRequestBodySizeChart object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202309PartialEditProductRequestBodySizeChartWithDefaults() *Product202309PartialEditProductRequestBodySizeChart {
    this := Product202309PartialEditProductRequestBodySizeChart{}
    return &this
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *Product202309PartialEditProductRequestBodySizeChart) GetImage() Product202309PartialEditProductRequestBodySizeChartImage {
    if o == nil || utils.IsNil(o.Image) {
        var ret Product202309PartialEditProductRequestBodySizeChartImage
        return ret
    }
    return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309PartialEditProductRequestBodySizeChart) GetImageOk() (*Product202309PartialEditProductRequestBodySizeChartImage, bool) {
    if o == nil || utils.IsNil(o.Image) {
        return nil, false
    }
    return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *Product202309PartialEditProductRequestBodySizeChart) HasImage() bool {
    if o != nil && !utils.IsNil(o.Image) {
        return true
    }

    return false
}

// SetImage gets a reference to the given Product202309PartialEditProductRequestBodySizeChartImage and assigns it to the Image field.
func (o *Product202309PartialEditProductRequestBodySizeChart) SetImage(v Product202309PartialEditProductRequestBodySizeChartImage) {
    o.Image = &v
}

// GetTemplate returns the Template field value if set, zero value otherwise.
func (o *Product202309PartialEditProductRequestBodySizeChart) GetTemplate() Product202309PartialEditProductRequestBodySizeChartTemplate {
    if o == nil || utils.IsNil(o.Template) {
        var ret Product202309PartialEditProductRequestBodySizeChartTemplate
        return ret
    }
    return *o.Template
}

// GetTemplateOk returns a tuple with the Template field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309PartialEditProductRequestBodySizeChart) GetTemplateOk() (*Product202309PartialEditProductRequestBodySizeChartTemplate, bool) {
    if o == nil || utils.IsNil(o.Template) {
        return nil, false
    }
    return o.Template, true
}

// HasTemplate returns a boolean if a field has been set.
func (o *Product202309PartialEditProductRequestBodySizeChart) HasTemplate() bool {
    if o != nil && !utils.IsNil(o.Template) {
        return true
    }

    return false
}

// SetTemplate gets a reference to the given Product202309PartialEditProductRequestBodySizeChartTemplate and assigns it to the Template field.
func (o *Product202309PartialEditProductRequestBodySizeChart) SetTemplate(v Product202309PartialEditProductRequestBodySizeChartTemplate) {
    o.Template = &v
}

func (o Product202309PartialEditProductRequestBodySizeChart) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202309PartialEditProductRequestBodySizeChart) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Image) {
        toSerialize["image"] = o.Image
    }
    if !utils.IsNil(o.Template) {
        toSerialize["template"] = o.Template
    }
    return toSerialize, nil
}

type NullableProduct202309PartialEditProductRequestBodySizeChart struct {
	value *Product202309PartialEditProductRequestBodySizeChart
	isSet bool
}

func (v NullableProduct202309PartialEditProductRequestBodySizeChart) Get() *Product202309PartialEditProductRequestBodySizeChart {
	return v.value
}

func (v *NullableProduct202309PartialEditProductRequestBodySizeChart) Set(val *Product202309PartialEditProductRequestBodySizeChart) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202309PartialEditProductRequestBodySizeChart) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202309PartialEditProductRequestBodySizeChart) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202309PartialEditProductRequestBodySizeChart(val *Product202309PartialEditProductRequestBodySizeChart) *NullableProduct202309PartialEditProductRequestBodySizeChart {
	return &NullableProduct202309PartialEditProductRequestBodySizeChart{value: val, isSet: true}
}

func (v NullableProduct202309PartialEditProductRequestBodySizeChart) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202309PartialEditProductRequestBodySizeChart) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


