/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202309RecommendGlobalCategoriesRequestBodyImages type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202309RecommendGlobalCategoriesRequestBodyImages{}

// Product202309RecommendGlobalCategoriesRequestBodyImages struct for Product202309RecommendGlobalCategoriesRequestBodyImages
type Product202309RecommendGlobalCategoriesRequestBodyImages struct {
    // The URI of the image. Retrieve the URI from the [Upload Product Image API](https://partner.tiktokshop.com/docv2/page/6509df95defece02be598a22).
    Uri *string `json:"uri,omitempty"`
}

// NewProduct202309RecommendGlobalCategoriesRequestBodyImages instantiates a new Product202309RecommendGlobalCategoriesRequestBodyImages object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202309RecommendGlobalCategoriesRequestBodyImages() *Product202309RecommendGlobalCategoriesRequestBodyImages {
    this := Product202309RecommendGlobalCategoriesRequestBodyImages{}
    return &this
}

// NewProduct202309RecommendGlobalCategoriesRequestBodyImagesWithDefaults instantiates a new Product202309RecommendGlobalCategoriesRequestBodyImages object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202309RecommendGlobalCategoriesRequestBodyImagesWithDefaults() *Product202309RecommendGlobalCategoriesRequestBodyImages {
    this := Product202309RecommendGlobalCategoriesRequestBodyImages{}
    return &this
}

// GetUri returns the Uri field value if set, zero value otherwise.
func (o *Product202309RecommendGlobalCategoriesRequestBodyImages) GetUri() string {
    if o == nil || utils.IsNil(o.Uri) {
        var ret string
        return ret
    }
    return *o.Uri
}

// GetUriOk returns a tuple with the Uri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309RecommendGlobalCategoriesRequestBodyImages) GetUriOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Uri) {
        return nil, false
    }
    return o.Uri, true
}

// HasUri returns a boolean if a field has been set.
func (o *Product202309RecommendGlobalCategoriesRequestBodyImages) HasUri() bool {
    if o != nil && !utils.IsNil(o.Uri) {
        return true
    }

    return false
}

// SetUri gets a reference to the given string and assigns it to the Uri field.
func (o *Product202309RecommendGlobalCategoriesRequestBodyImages) SetUri(v string) {
    o.Uri = &v
}

func (o Product202309RecommendGlobalCategoriesRequestBodyImages) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202309RecommendGlobalCategoriesRequestBodyImages) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Uri) {
        toSerialize["uri"] = o.Uri
    }
    return toSerialize, nil
}

type NullableProduct202309RecommendGlobalCategoriesRequestBodyImages struct {
	value *Product202309RecommendGlobalCategoriesRequestBodyImages
	isSet bool
}

func (v NullableProduct202309RecommendGlobalCategoriesRequestBodyImages) Get() *Product202309RecommendGlobalCategoriesRequestBodyImages {
	return v.value
}

func (v *NullableProduct202309RecommendGlobalCategoriesRequestBodyImages) Set(val *Product202309RecommendGlobalCategoriesRequestBodyImages) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202309RecommendGlobalCategoriesRequestBodyImages) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202309RecommendGlobalCategoriesRequestBodyImages) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202309RecommendGlobalCategoriesRequestBodyImages(val *Product202309RecommendGlobalCategoriesRequestBodyImages) *NullableProduct202309RecommendGlobalCategoriesRequestBodyImages {
	return &NullableProduct202309RecommendGlobalCategoriesRequestBodyImages{value: val, isSet: true}
}

func (v NullableProduct202309RecommendGlobalCategoriesRequestBodyImages) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202309RecommendGlobalCategoriesRequestBodyImages) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


