/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202309RecoverProductsResponseData type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202309RecoverProductsResponseData{}

// Product202309RecoverProductsResponseData struct for Product202309RecoverProductsResponseData
type Product202309RecoverProductsResponseData struct {
    // The list of errors that occurred.
    Errors []Product202309RecoverProductsResponseDataErrors `json:"errors,omitempty"`
}

// NewProduct202309RecoverProductsResponseData instantiates a new Product202309RecoverProductsResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202309RecoverProductsResponseData() *Product202309RecoverProductsResponseData {
    this := Product202309RecoverProductsResponseData{}
    return &this
}

// NewProduct202309RecoverProductsResponseDataWithDefaults instantiates a new Product202309RecoverProductsResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202309RecoverProductsResponseDataWithDefaults() *Product202309RecoverProductsResponseData {
    this := Product202309RecoverProductsResponseData{}
    return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *Product202309RecoverProductsResponseData) GetErrors() []Product202309RecoverProductsResponseDataErrors {
    if o == nil || utils.IsNil(o.Errors) {
        var ret []Product202309RecoverProductsResponseDataErrors
        return ret
    }
    return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202309RecoverProductsResponseData) GetErrorsOk() ([]Product202309RecoverProductsResponseDataErrors, bool) {
    if o == nil || utils.IsNil(o.Errors) {
        return nil, false
    }
    return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *Product202309RecoverProductsResponseData) HasErrors() bool {
    if o != nil && !utils.IsNil(o.Errors) {
        return true
    }

    return false
}

// SetErrors gets a reference to the given []Product202309RecoverProductsResponseDataErrors and assigns it to the Errors field.
func (o *Product202309RecoverProductsResponseData) SetErrors(v []Product202309RecoverProductsResponseDataErrors) {
    o.Errors = v
}

func (o Product202309RecoverProductsResponseData) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202309RecoverProductsResponseData) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Errors) {
        toSerialize["errors"] = o.Errors
    }
    return toSerialize, nil
}

type NullableProduct202309RecoverProductsResponseData struct {
	value *Product202309RecoverProductsResponseData
	isSet bool
}

func (v NullableProduct202309RecoverProductsResponseData) Get() *Product202309RecoverProductsResponseData {
	return v.value
}

func (v *NullableProduct202309RecoverProductsResponseData) Set(val *Product202309RecoverProductsResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202309RecoverProductsResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202309RecoverProductsResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202309RecoverProductsResponseData(val *Product202309RecoverProductsResponseData) *NullableProduct202309RecoverProductsResponseData {
	return &NullableProduct202309RecoverProductsResponseData{value: val, isSet: true}
}

func (v NullableProduct202309RecoverProductsResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202309RecoverProductsResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


