/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202405

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions{}

// Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions struct for Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions
type Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions struct {
    // The applicable product field. Possible values: - TITLE - DESCRIPTION
    Field *string `json:"field,omitempty"`
    // The list of optimized text.
    Items []Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsItems `json:"items,omitempty"`
}

// NewProduct202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions instantiates a new Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions() *Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions {
    this := Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions{}
    return &this
}

// NewProduct202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsWithDefaults instantiates a new Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsWithDefaults() *Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions {
    this := Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions{}
    return &this
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions) GetField() string {
    if o == nil || utils.IsNil(o.Field) {
        var ret string
        return ret
    }
    return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions) GetFieldOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Field) {
        return nil, false
    }
    return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions) HasField() bool {
    if o != nil && !utils.IsNil(o.Field) {
        return true
    }

    return false
}

// SetField gets a reference to the given string and assigns it to the Field field.
func (o *Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions) SetField(v string) {
    o.Field = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions) GetItems() []Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsItems {
    if o == nil || utils.IsNil(o.Items) {
        var ret []Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsItems
        return ret
    }
    return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions) GetItemsOk() ([]Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsItems, bool) {
    if o == nil || utils.IsNil(o.Items) {
        return nil, false
    }
    return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions) HasItems() bool {
    if o != nil && !utils.IsNil(o.Items) {
        return true
    }

    return false
}

// SetItems gets a reference to the given []Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsItems and assigns it to the Items field.
func (o *Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions) SetItems(v []Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsItems) {
    o.Items = v
}

func (o Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Field) {
        toSerialize["field"] = o.Field
    }
    if !utils.IsNil(o.Items) {
        toSerialize["items"] = o.Items
    }
    return toSerialize, nil
}

type NullableProduct202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions struct {
	value *Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions
	isSet bool
}

func (v NullableProduct202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions) Get() *Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions {
	return v.value
}

func (v *NullableProduct202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions) Set(val *Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions(val *Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions) *NullableProduct202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions {
	return &NullableProduct202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions{value: val, isSet: true}
}

func (v NullableProduct202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


