/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fulfillment_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Fulfillment202309SchedulePackageHandoverResponseDataDimension type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Fulfillment202309SchedulePackageHandoverResponseDataDimension{}

// Fulfillment202309SchedulePackageHandoverResponseDataDimension struct for Fulfillment202309SchedulePackageHandoverResponseDataDimension
type Fulfillment202309SchedulePackageHandoverResponseDataDimension struct {
    // The height of package. 
    Height *string `json:"height,omitempty"`
    // The length of package.
    Length *string `json:"length,omitempty"`
    // The unit of measurement is used to measure the length. - CM - INCH
    Unit *string `json:"unit,omitempty"`
    // The width of package. 
    Width *string `json:"width,omitempty"`
}

// NewFulfillment202309SchedulePackageHandoverResponseDataDimension instantiates a new Fulfillment202309SchedulePackageHandoverResponseDataDimension object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFulfillment202309SchedulePackageHandoverResponseDataDimension() *Fulfillment202309SchedulePackageHandoverResponseDataDimension {
    this := Fulfillment202309SchedulePackageHandoverResponseDataDimension{}
    return &this
}

// NewFulfillment202309SchedulePackageHandoverResponseDataDimensionWithDefaults instantiates a new Fulfillment202309SchedulePackageHandoverResponseDataDimension object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFulfillment202309SchedulePackageHandoverResponseDataDimensionWithDefaults() *Fulfillment202309SchedulePackageHandoverResponseDataDimension {
    this := Fulfillment202309SchedulePackageHandoverResponseDataDimension{}
    return &this
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *Fulfillment202309SchedulePackageHandoverResponseDataDimension) GetHeight() string {
    if o == nil || utils.IsNil(o.Height) {
        var ret string
        return ret
    }
    return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fulfillment202309SchedulePackageHandoverResponseDataDimension) GetHeightOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Height) {
        return nil, false
    }
    return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *Fulfillment202309SchedulePackageHandoverResponseDataDimension) HasHeight() bool {
    if o != nil && !utils.IsNil(o.Height) {
        return true
    }

    return false
}

// SetHeight gets a reference to the given string and assigns it to the Height field.
func (o *Fulfillment202309SchedulePackageHandoverResponseDataDimension) SetHeight(v string) {
    o.Height = &v
}

// GetLength returns the Length field value if set, zero value otherwise.
func (o *Fulfillment202309SchedulePackageHandoverResponseDataDimension) GetLength() string {
    if o == nil || utils.IsNil(o.Length) {
        var ret string
        return ret
    }
    return *o.Length
}

// GetLengthOk returns a tuple with the Length field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fulfillment202309SchedulePackageHandoverResponseDataDimension) GetLengthOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Length) {
        return nil, false
    }
    return o.Length, true
}

// HasLength returns a boolean if a field has been set.
func (o *Fulfillment202309SchedulePackageHandoverResponseDataDimension) HasLength() bool {
    if o != nil && !utils.IsNil(o.Length) {
        return true
    }

    return false
}

// SetLength gets a reference to the given string and assigns it to the Length field.
func (o *Fulfillment202309SchedulePackageHandoverResponseDataDimension) SetLength(v string) {
    o.Length = &v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *Fulfillment202309SchedulePackageHandoverResponseDataDimension) GetUnit() string {
    if o == nil || utils.IsNil(o.Unit) {
        var ret string
        return ret
    }
    return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fulfillment202309SchedulePackageHandoverResponseDataDimension) GetUnitOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Unit) {
        return nil, false
    }
    return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *Fulfillment202309SchedulePackageHandoverResponseDataDimension) HasUnit() bool {
    if o != nil && !utils.IsNil(o.Unit) {
        return true
    }

    return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *Fulfillment202309SchedulePackageHandoverResponseDataDimension) SetUnit(v string) {
    o.Unit = &v
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *Fulfillment202309SchedulePackageHandoverResponseDataDimension) GetWidth() string {
    if o == nil || utils.IsNil(o.Width) {
        var ret string
        return ret
    }
    return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fulfillment202309SchedulePackageHandoverResponseDataDimension) GetWidthOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Width) {
        return nil, false
    }
    return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *Fulfillment202309SchedulePackageHandoverResponseDataDimension) HasWidth() bool {
    if o != nil && !utils.IsNil(o.Width) {
        return true
    }

    return false
}

// SetWidth gets a reference to the given string and assigns it to the Width field.
func (o *Fulfillment202309SchedulePackageHandoverResponseDataDimension) SetWidth(v string) {
    o.Width = &v
}

func (o Fulfillment202309SchedulePackageHandoverResponseDataDimension) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Fulfillment202309SchedulePackageHandoverResponseDataDimension) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Height) {
        toSerialize["height"] = o.Height
    }
    if !utils.IsNil(o.Length) {
        toSerialize["length"] = o.Length
    }
    if !utils.IsNil(o.Unit) {
        toSerialize["unit"] = o.Unit
    }
    if !utils.IsNil(o.Width) {
        toSerialize["width"] = o.Width
    }
    return toSerialize, nil
}

type NullableFulfillment202309SchedulePackageHandoverResponseDataDimension struct {
	value *Fulfillment202309SchedulePackageHandoverResponseDataDimension
	isSet bool
}

func (v NullableFulfillment202309SchedulePackageHandoverResponseDataDimension) Get() *Fulfillment202309SchedulePackageHandoverResponseDataDimension {
	return v.value
}

func (v *NullableFulfillment202309SchedulePackageHandoverResponseDataDimension) Set(val *Fulfillment202309SchedulePackageHandoverResponseDataDimension) {
	v.value = val
	v.isSet = true
}

func (v NullableFulfillment202309SchedulePackageHandoverResponseDataDimension) IsSet() bool {
	return v.isSet
}

func (v *NullableFulfillment202309SchedulePackageHandoverResponseDataDimension) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFulfillment202309SchedulePackageHandoverResponseDataDimension(val *Fulfillment202309SchedulePackageHandoverResponseDataDimension) *NullableFulfillment202309SchedulePackageHandoverResponseDataDimension {
	return &NullableFulfillment202309SchedulePackageHandoverResponseDataDimension{value: val, isSet: true}
}

func (v NullableFulfillment202309SchedulePackageHandoverResponseDataDimension) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFulfillment202309SchedulePackageHandoverResponseDataDimension) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


