/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fulfillment_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Fulfillment202309SplitOrdersRequestBodySplittableGroups type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Fulfillment202309SplitOrdersRequestBodySplittableGroups{}

// Fulfillment202309SplitOrdersRequestBodySplittableGroups struct for Fulfillment202309SplitOrdersRequestBodySplittableGroups
type Fulfillment202309SplitOrdersRequestBodySplittableGroups struct {
    // A unique identifier designated by the developer. This identifier will represent a group of items that will be split into a new package. Once split is confirmed, the platform will be assigned a new package ID for this group of items.  For example, if you input `123` as request, the response will return `123` as your unique identification. The seller uses this field to label each group of items that have been split, and the platform will assign new package IDs to them. 
    Id *string `json:"id,omitempty"`
    // The order line item IDs that need to be split into this group.
    OrderLineItemIds []string `json:"order_line_item_ids,omitempty"`
}

// NewFulfillment202309SplitOrdersRequestBodySplittableGroups instantiates a new Fulfillment202309SplitOrdersRequestBodySplittableGroups object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFulfillment202309SplitOrdersRequestBodySplittableGroups() *Fulfillment202309SplitOrdersRequestBodySplittableGroups {
    this := Fulfillment202309SplitOrdersRequestBodySplittableGroups{}
    return &this
}

// NewFulfillment202309SplitOrdersRequestBodySplittableGroupsWithDefaults instantiates a new Fulfillment202309SplitOrdersRequestBodySplittableGroups object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFulfillment202309SplitOrdersRequestBodySplittableGroupsWithDefaults() *Fulfillment202309SplitOrdersRequestBodySplittableGroups {
    this := Fulfillment202309SplitOrdersRequestBodySplittableGroups{}
    return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Fulfillment202309SplitOrdersRequestBodySplittableGroups) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fulfillment202309SplitOrdersRequestBodySplittableGroups) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Fulfillment202309SplitOrdersRequestBodySplittableGroups) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Fulfillment202309SplitOrdersRequestBodySplittableGroups) SetId(v string) {
    o.Id = &v
}

// GetOrderLineItemIds returns the OrderLineItemIds field value if set, zero value otherwise.
func (o *Fulfillment202309SplitOrdersRequestBodySplittableGroups) GetOrderLineItemIds() []string {
    if o == nil || utils.IsNil(o.OrderLineItemIds) {
        var ret []string
        return ret
    }
    return o.OrderLineItemIds
}

// GetOrderLineItemIdsOk returns a tuple with the OrderLineItemIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fulfillment202309SplitOrdersRequestBodySplittableGroups) GetOrderLineItemIdsOk() ([]string, bool) {
    if o == nil || utils.IsNil(o.OrderLineItemIds) {
        return nil, false
    }
    return o.OrderLineItemIds, true
}

// HasOrderLineItemIds returns a boolean if a field has been set.
func (o *Fulfillment202309SplitOrdersRequestBodySplittableGroups) HasOrderLineItemIds() bool {
    if o != nil && !utils.IsNil(o.OrderLineItemIds) {
        return true
    }

    return false
}

// SetOrderLineItemIds gets a reference to the given []string and assigns it to the OrderLineItemIds field.
func (o *Fulfillment202309SplitOrdersRequestBodySplittableGroups) SetOrderLineItemIds(v []string) {
    o.OrderLineItemIds = v
}

func (o Fulfillment202309SplitOrdersRequestBodySplittableGroups) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Fulfillment202309SplitOrdersRequestBodySplittableGroups) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }
    if !utils.IsNil(o.OrderLineItemIds) {
        toSerialize["order_line_item_ids"] = o.OrderLineItemIds
    }
    return toSerialize, nil
}

type NullableFulfillment202309SplitOrdersRequestBodySplittableGroups struct {
	value *Fulfillment202309SplitOrdersRequestBodySplittableGroups
	isSet bool
}

func (v NullableFulfillment202309SplitOrdersRequestBodySplittableGroups) Get() *Fulfillment202309SplitOrdersRequestBodySplittableGroups {
	return v.value
}

func (v *NullableFulfillment202309SplitOrdersRequestBodySplittableGroups) Set(val *Fulfillment202309SplitOrdersRequestBodySplittableGroups) {
	v.value = val
	v.isSet = true
}

func (v NullableFulfillment202309SplitOrdersRequestBodySplittableGroups) IsSet() bool {
	return v.isSet
}

func (v *NullableFulfillment202309SplitOrdersRequestBodySplittableGroups) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFulfillment202309SplitOrdersRequestBodySplittableGroups(val *Fulfillment202309SplitOrdersRequestBodySplittableGroups) *NullableFulfillment202309SplitOrdersRequestBodySplittableGroups {
	return &NullableFulfillment202309SplitOrdersRequestBodySplittableGroups{value: val, isSet: true}
}

func (v NullableFulfillment202309SplitOrdersRequestBodySplittableGroups) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFulfillment202309SplitOrdersRequestBodySplittableGroups) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


