/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fulfillment_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Fulfillment202309UpdatePackageDeliveryStatusRequestBody type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Fulfillment202309UpdatePackageDeliveryStatusRequestBody{}

// Fulfillment202309UpdatePackageDeliveryStatusRequestBody struct for Fulfillment202309UpdatePackageDeliveryStatusRequestBody
type Fulfillment202309UpdatePackageDeliveryStatusRequestBody struct {
    // The return list of packages.
    Packages []Fulfillment202309UpdatePackageDeliveryStatusRequestBodyPackages `json:"packages,omitempty"`
}

// NewFulfillment202309UpdatePackageDeliveryStatusRequestBody instantiates a new Fulfillment202309UpdatePackageDeliveryStatusRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFulfillment202309UpdatePackageDeliveryStatusRequestBody() *Fulfillment202309UpdatePackageDeliveryStatusRequestBody {
    this := Fulfillment202309UpdatePackageDeliveryStatusRequestBody{}
    return &this
}

// NewFulfillment202309UpdatePackageDeliveryStatusRequestBodyWithDefaults instantiates a new Fulfillment202309UpdatePackageDeliveryStatusRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFulfillment202309UpdatePackageDeliveryStatusRequestBodyWithDefaults() *Fulfillment202309UpdatePackageDeliveryStatusRequestBody {
    this := Fulfillment202309UpdatePackageDeliveryStatusRequestBody{}
    return &this
}

// GetPackages returns the Packages field value if set, zero value otherwise.
func (o *Fulfillment202309UpdatePackageDeliveryStatusRequestBody) GetPackages() []Fulfillment202309UpdatePackageDeliveryStatusRequestBodyPackages {
    if o == nil || utils.IsNil(o.Packages) {
        var ret []Fulfillment202309UpdatePackageDeliveryStatusRequestBodyPackages
        return ret
    }
    return o.Packages
}

// GetPackagesOk returns a tuple with the Packages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fulfillment202309UpdatePackageDeliveryStatusRequestBody) GetPackagesOk() ([]Fulfillment202309UpdatePackageDeliveryStatusRequestBodyPackages, bool) {
    if o == nil || utils.IsNil(o.Packages) {
        return nil, false
    }
    return o.Packages, true
}

// HasPackages returns a boolean if a field has been set.
func (o *Fulfillment202309UpdatePackageDeliveryStatusRequestBody) HasPackages() bool {
    if o != nil && !utils.IsNil(o.Packages) {
        return true
    }

    return false
}

// SetPackages gets a reference to the given []Fulfillment202309UpdatePackageDeliveryStatusRequestBodyPackages and assigns it to the Packages field.
func (o *Fulfillment202309UpdatePackageDeliveryStatusRequestBody) SetPackages(v []Fulfillment202309UpdatePackageDeliveryStatusRequestBodyPackages) {
    o.Packages = v
}

func (o Fulfillment202309UpdatePackageDeliveryStatusRequestBody) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Fulfillment202309UpdatePackageDeliveryStatusRequestBody) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Packages) {
        toSerialize["packages"] = o.Packages
    }
    return toSerialize, nil
}

type NullableFulfillment202309UpdatePackageDeliveryStatusRequestBody struct {
	value *Fulfillment202309UpdatePackageDeliveryStatusRequestBody
	isSet bool
}

func (v NullableFulfillment202309UpdatePackageDeliveryStatusRequestBody) Get() *Fulfillment202309UpdatePackageDeliveryStatusRequestBody {
	return v.value
}

func (v *NullableFulfillment202309UpdatePackageDeliveryStatusRequestBody) Set(val *Fulfillment202309UpdatePackageDeliveryStatusRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableFulfillment202309UpdatePackageDeliveryStatusRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableFulfillment202309UpdatePackageDeliveryStatusRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFulfillment202309UpdatePackageDeliveryStatusRequestBody(val *Fulfillment202309UpdatePackageDeliveryStatusRequestBody) *NullableFulfillment202309UpdatePackageDeliveryStatusRequestBody {
	return &NullableFulfillment202309UpdatePackageDeliveryStatusRequestBody{value: val, isSet: true}
}

func (v NullableFulfillment202309UpdatePackageDeliveryStatusRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFulfillment202309UpdatePackageDeliveryStatusRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


