/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fulfillment_v202502

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Fulfillment202502UploadInvoiceRequestBodyInvoices type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Fulfillment202502UploadInvoiceRequestBodyInvoices{}

// Fulfillment202502UploadInvoiceRequestBodyInvoices struct for Fulfillment202502UploadInvoiceRequestBodyInvoices
type Fulfillment202502UploadInvoiceRequestBodyInvoices struct {
    // Base64 encoding of the invoice file to upload. Max file size: 1MB
    File *string `json:"file,omitempty"`
    // The invoice file format. Possible values:  - `XML`
    FileType *string `json:"file_type,omitempty"`
    // The list of TikTok Shop order IDs, retrieved from [Get Order List](650aa8094a0bb702c06df242).
    OrderIds []string `json:"order_ids,omitempty"`
    // The TikTok Shop package ID, retrieved from [Search Package](650aa592bace3e02b75db748).
    PackageId *string `json:"package_id,omitempty"`
}

// NewFulfillment202502UploadInvoiceRequestBodyInvoices instantiates a new Fulfillment202502UploadInvoiceRequestBodyInvoices object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFulfillment202502UploadInvoiceRequestBodyInvoices() *Fulfillment202502UploadInvoiceRequestBodyInvoices {
    this := Fulfillment202502UploadInvoiceRequestBodyInvoices{}
    return &this
}

// NewFulfillment202502UploadInvoiceRequestBodyInvoicesWithDefaults instantiates a new Fulfillment202502UploadInvoiceRequestBodyInvoices object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFulfillment202502UploadInvoiceRequestBodyInvoicesWithDefaults() *Fulfillment202502UploadInvoiceRequestBodyInvoices {
    this := Fulfillment202502UploadInvoiceRequestBodyInvoices{}
    return &this
}

// GetFile returns the File field value if set, zero value otherwise.
func (o *Fulfillment202502UploadInvoiceRequestBodyInvoices) GetFile() string {
    if o == nil || utils.IsNil(o.File) {
        var ret string
        return ret
    }
    return *o.File
}

// GetFileOk returns a tuple with the File field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fulfillment202502UploadInvoiceRequestBodyInvoices) GetFileOk() (*string, bool) {
    if o == nil || utils.IsNil(o.File) {
        return nil, false
    }
    return o.File, true
}

// HasFile returns a boolean if a field has been set.
func (o *Fulfillment202502UploadInvoiceRequestBodyInvoices) HasFile() bool {
    if o != nil && !utils.IsNil(o.File) {
        return true
    }

    return false
}

// SetFile gets a reference to the given string and assigns it to the File field.
func (o *Fulfillment202502UploadInvoiceRequestBodyInvoices) SetFile(v string) {
    o.File = &v
}

// GetFileType returns the FileType field value if set, zero value otherwise.
func (o *Fulfillment202502UploadInvoiceRequestBodyInvoices) GetFileType() string {
    if o == nil || utils.IsNil(o.FileType) {
        var ret string
        return ret
    }
    return *o.FileType
}

// GetFileTypeOk returns a tuple with the FileType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fulfillment202502UploadInvoiceRequestBodyInvoices) GetFileTypeOk() (*string, bool) {
    if o == nil || utils.IsNil(o.FileType) {
        return nil, false
    }
    return o.FileType, true
}

// HasFileType returns a boolean if a field has been set.
func (o *Fulfillment202502UploadInvoiceRequestBodyInvoices) HasFileType() bool {
    if o != nil && !utils.IsNil(o.FileType) {
        return true
    }

    return false
}

// SetFileType gets a reference to the given string and assigns it to the FileType field.
func (o *Fulfillment202502UploadInvoiceRequestBodyInvoices) SetFileType(v string) {
    o.FileType = &v
}

// GetOrderIds returns the OrderIds field value if set, zero value otherwise.
func (o *Fulfillment202502UploadInvoiceRequestBodyInvoices) GetOrderIds() []string {
    if o == nil || utils.IsNil(o.OrderIds) {
        var ret []string
        return ret
    }
    return o.OrderIds
}

// GetOrderIdsOk returns a tuple with the OrderIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fulfillment202502UploadInvoiceRequestBodyInvoices) GetOrderIdsOk() ([]string, bool) {
    if o == nil || utils.IsNil(o.OrderIds) {
        return nil, false
    }
    return o.OrderIds, true
}

// HasOrderIds returns a boolean if a field has been set.
func (o *Fulfillment202502UploadInvoiceRequestBodyInvoices) HasOrderIds() bool {
    if o != nil && !utils.IsNil(o.OrderIds) {
        return true
    }

    return false
}

// SetOrderIds gets a reference to the given []string and assigns it to the OrderIds field.
func (o *Fulfillment202502UploadInvoiceRequestBodyInvoices) SetOrderIds(v []string) {
    o.OrderIds = v
}

// GetPackageId returns the PackageId field value if set, zero value otherwise.
func (o *Fulfillment202502UploadInvoiceRequestBodyInvoices) GetPackageId() string {
    if o == nil || utils.IsNil(o.PackageId) {
        var ret string
        return ret
    }
    return *o.PackageId
}

// GetPackageIdOk returns a tuple with the PackageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fulfillment202502UploadInvoiceRequestBodyInvoices) GetPackageIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.PackageId) {
        return nil, false
    }
    return o.PackageId, true
}

// HasPackageId returns a boolean if a field has been set.
func (o *Fulfillment202502UploadInvoiceRequestBodyInvoices) HasPackageId() bool {
    if o != nil && !utils.IsNil(o.PackageId) {
        return true
    }

    return false
}

// SetPackageId gets a reference to the given string and assigns it to the PackageId field.
func (o *Fulfillment202502UploadInvoiceRequestBodyInvoices) SetPackageId(v string) {
    o.PackageId = &v
}

func (o Fulfillment202502UploadInvoiceRequestBodyInvoices) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Fulfillment202502UploadInvoiceRequestBodyInvoices) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.File) {
        toSerialize["file"] = o.File
    }
    if !utils.IsNil(o.FileType) {
        toSerialize["file_type"] = o.FileType
    }
    if !utils.IsNil(o.OrderIds) {
        toSerialize["order_ids"] = o.OrderIds
    }
    if !utils.IsNil(o.PackageId) {
        toSerialize["package_id"] = o.PackageId
    }
    return toSerialize, nil
}

type NullableFulfillment202502UploadInvoiceRequestBodyInvoices struct {
	value *Fulfillment202502UploadInvoiceRequestBodyInvoices
	isSet bool
}

func (v NullableFulfillment202502UploadInvoiceRequestBodyInvoices) Get() *Fulfillment202502UploadInvoiceRequestBodyInvoices {
	return v.value
}

func (v *NullableFulfillment202502UploadInvoiceRequestBodyInvoices) Set(val *Fulfillment202502UploadInvoiceRequestBodyInvoices) {
	v.value = val
	v.isSet = true
}

func (v NullableFulfillment202502UploadInvoiceRequestBodyInvoices) IsSet() bool {
	return v.isSet
}

func (v *NullableFulfillment202502UploadInvoiceRequestBodyInvoices) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFulfillment202502UploadInvoiceRequestBodyInvoices(val *Fulfillment202502UploadInvoiceRequestBodyInvoices) *NullableFulfillment202502UploadInvoiceRequestBodyInvoices {
	return &NullableFulfillment202502UploadInvoiceRequestBodyInvoices{value: val, isSet: true}
}

func (v NullableFulfillment202502UploadInvoiceRequestBodyInvoices) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFulfillment202502UploadInvoiceRequestBodyInvoices) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


