/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202501

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202501SearchResponsiblePersonsResponseDataResponsiblePersons type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202501SearchResponsiblePersonsResponseDataResponsiblePersons{}

// Product202501SearchResponsiblePersonsResponseDataResponsiblePersons struct for Product202501SearchResponsiblePersonsResponseDataResponsiblePersons
type Product202501SearchResponsiblePersonsResponseDataResponsiblePersons struct {
    // The responsible person ID in TikTok Shop.
    Id *string `json:"id,omitempty"`
    // A list of contact details for the responsible person, presented in different languages for each supported EU country.
    RegionalProfiles []Product202501SearchResponsiblePersonsResponseDataResponsiblePersonsRegionalProfiles `json:"regional_profiles,omitempty"`
}

// NewProduct202501SearchResponsiblePersonsResponseDataResponsiblePersons instantiates a new Product202501SearchResponsiblePersonsResponseDataResponsiblePersons object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202501SearchResponsiblePersonsResponseDataResponsiblePersons() *Product202501SearchResponsiblePersonsResponseDataResponsiblePersons {
    this := Product202501SearchResponsiblePersonsResponseDataResponsiblePersons{}
    return &this
}

// NewProduct202501SearchResponsiblePersonsResponseDataResponsiblePersonsWithDefaults instantiates a new Product202501SearchResponsiblePersonsResponseDataResponsiblePersons object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202501SearchResponsiblePersonsResponseDataResponsiblePersonsWithDefaults() *Product202501SearchResponsiblePersonsResponseDataResponsiblePersons {
    this := Product202501SearchResponsiblePersonsResponseDataResponsiblePersons{}
    return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Product202501SearchResponsiblePersonsResponseDataResponsiblePersons) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202501SearchResponsiblePersonsResponseDataResponsiblePersons) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Product202501SearchResponsiblePersonsResponseDataResponsiblePersons) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Product202501SearchResponsiblePersonsResponseDataResponsiblePersons) SetId(v string) {
    o.Id = &v
}

// GetRegionalProfiles returns the RegionalProfiles field value if set, zero value otherwise.
func (o *Product202501SearchResponsiblePersonsResponseDataResponsiblePersons) GetRegionalProfiles() []Product202501SearchResponsiblePersonsResponseDataResponsiblePersonsRegionalProfiles {
    if o == nil || utils.IsNil(o.RegionalProfiles) {
        var ret []Product202501SearchResponsiblePersonsResponseDataResponsiblePersonsRegionalProfiles
        return ret
    }
    return o.RegionalProfiles
}

// GetRegionalProfilesOk returns a tuple with the RegionalProfiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202501SearchResponsiblePersonsResponseDataResponsiblePersons) GetRegionalProfilesOk() ([]Product202501SearchResponsiblePersonsResponseDataResponsiblePersonsRegionalProfiles, bool) {
    if o == nil || utils.IsNil(o.RegionalProfiles) {
        return nil, false
    }
    return o.RegionalProfiles, true
}

// HasRegionalProfiles returns a boolean if a field has been set.
func (o *Product202501SearchResponsiblePersonsResponseDataResponsiblePersons) HasRegionalProfiles() bool {
    if o != nil && !utils.IsNil(o.RegionalProfiles) {
        return true
    }

    return false
}

// SetRegionalProfiles gets a reference to the given []Product202501SearchResponsiblePersonsResponseDataResponsiblePersonsRegionalProfiles and assigns it to the RegionalProfiles field.
func (o *Product202501SearchResponsiblePersonsResponseDataResponsiblePersons) SetRegionalProfiles(v []Product202501SearchResponsiblePersonsResponseDataResponsiblePersonsRegionalProfiles) {
    o.RegionalProfiles = v
}

func (o Product202501SearchResponsiblePersonsResponseDataResponsiblePersons) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202501SearchResponsiblePersonsResponseDataResponsiblePersons) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }
    if !utils.IsNil(o.RegionalProfiles) {
        toSerialize["regional_profiles"] = o.RegionalProfiles
    }
    return toSerialize, nil
}

type NullableProduct202501SearchResponsiblePersonsResponseDataResponsiblePersons struct {
	value *Product202501SearchResponsiblePersonsResponseDataResponsiblePersons
	isSet bool
}

func (v NullableProduct202501SearchResponsiblePersonsResponseDataResponsiblePersons) Get() *Product202501SearchResponsiblePersonsResponseDataResponsiblePersons {
	return v.value
}

func (v *NullableProduct202501SearchResponsiblePersonsResponseDataResponsiblePersons) Set(val *Product202501SearchResponsiblePersonsResponseDataResponsiblePersons) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202501SearchResponsiblePersonsResponseDataResponsiblePersons) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202501SearchResponsiblePersonsResponseDataResponsiblePersons) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202501SearchResponsiblePersonsResponseDataResponsiblePersons(val *Product202501SearchResponsiblePersonsResponseDataResponsiblePersons) *NullableProduct202501SearchResponsiblePersonsResponseDataResponsiblePersons {
	return &NullableProduct202501SearchResponsiblePersonsResponseDataResponsiblePersons{value: val, isSet: true}
}

func (v NullableProduct202501SearchResponsiblePersonsResponseDataResponsiblePersons) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202501SearchResponsiblePersonsResponseDataResponsiblePersons) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


