/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authorization_v202403

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Authorization202403DeauthorizeShopResponse type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Authorization202403DeauthorizeShopResponse{}

// Authorization202403DeauthorizeShopResponse struct for Authorization202403DeauthorizeShopResponse
type Authorization202403DeauthorizeShopResponse struct {
    // The success or failure status code returned in API response.
    Code *int32 `json:"code,omitempty"`
    Data map[string]interface{} `json:"data,omitempty"`
    // The success or failure messages returned in API response. Reasons of failure will be described in the message.
    Message *string `json:"message,omitempty"`
    // Request log.
    RequestId *string `json:"request_id,omitempty"`
}

// NewAuthorization202403DeauthorizeShopResponse instantiates a new Authorization202403DeauthorizeShopResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorization202403DeauthorizeShopResponse() *Authorization202403DeauthorizeShopResponse {
    this := Authorization202403DeauthorizeShopResponse{}
    return &this
}

// NewAuthorization202403DeauthorizeShopResponseWithDefaults instantiates a new Authorization202403DeauthorizeShopResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorization202403DeauthorizeShopResponseWithDefaults() *Authorization202403DeauthorizeShopResponse {
    this := Authorization202403DeauthorizeShopResponse{}
    return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *Authorization202403DeauthorizeShopResponse) GetCode() int32 {
    if o == nil || utils.IsNil(o.Code) {
        var ret int32
        return ret
    }
    return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Authorization202403DeauthorizeShopResponse) GetCodeOk() (*int32, bool) {
    if o == nil || utils.IsNil(o.Code) {
        return nil, false
    }
    return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *Authorization202403DeauthorizeShopResponse) HasCode() bool {
    if o != nil && !utils.IsNil(o.Code) {
        return true
    }

    return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *Authorization202403DeauthorizeShopResponse) SetCode(v int32) {
    o.Code = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *Authorization202403DeauthorizeShopResponse) GetData() map[string]interface{} {
    if o == nil || utils.IsNil(o.Data) {
        var ret map[string]interface{}
        return ret
    }
    return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Authorization202403DeauthorizeShopResponse) GetDataOk() (map[string]interface{}, bool) {
    if o == nil || utils.IsNil(o.Data) {
        return map[string]interface{}{}, false
    }
    return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *Authorization202403DeauthorizeShopResponse) HasData() bool {
    if o != nil && !utils.IsNil(o.Data) {
        return true
    }

    return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *Authorization202403DeauthorizeShopResponse) SetData(v map[string]interface{}) {
    o.Data = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *Authorization202403DeauthorizeShopResponse) GetMessage() string {
    if o == nil || utils.IsNil(o.Message) {
        var ret string
        return ret
    }
    return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Authorization202403DeauthorizeShopResponse) GetMessageOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Message) {
        return nil, false
    }
    return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *Authorization202403DeauthorizeShopResponse) HasMessage() bool {
    if o != nil && !utils.IsNil(o.Message) {
        return true
    }

    return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *Authorization202403DeauthorizeShopResponse) SetMessage(v string) {
    o.Message = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *Authorization202403DeauthorizeShopResponse) GetRequestId() string {
    if o == nil || utils.IsNil(o.RequestId) {
        var ret string
        return ret
    }
    return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Authorization202403DeauthorizeShopResponse) GetRequestIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.RequestId) {
        return nil, false
    }
    return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *Authorization202403DeauthorizeShopResponse) HasRequestId() bool {
    if o != nil && !utils.IsNil(o.RequestId) {
        return true
    }

    return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *Authorization202403DeauthorizeShopResponse) SetRequestId(v string) {
    o.RequestId = &v
}

func (o Authorization202403DeauthorizeShopResponse) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Authorization202403DeauthorizeShopResponse) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Code) {
        toSerialize["code"] = o.Code
    }
    if !utils.IsNil(o.Data) {
        toSerialize["data"] = o.Data
    }
    if !utils.IsNil(o.Message) {
        toSerialize["message"] = o.Message
    }
    if !utils.IsNil(o.RequestId) {
        toSerialize["request_id"] = o.RequestId
    }
    return toSerialize, nil
}

type NullableAuthorization202403DeauthorizeShopResponse struct {
	value *Authorization202403DeauthorizeShopResponse
	isSet bool
}

func (v NullableAuthorization202403DeauthorizeShopResponse) Get() *Authorization202403DeauthorizeShopResponse {
	return v.value
}

func (v *NullableAuthorization202403DeauthorizeShopResponse) Set(val *Authorization202403DeauthorizeShopResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorization202403DeauthorizeShopResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorization202403DeauthorizeShopResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorization202403DeauthorizeShopResponse(val *Authorization202403DeauthorizeShopResponse) *NullableAuthorization202403DeauthorizeShopResponse {
	return &NullableAuthorization202403DeauthorizeShopResponse{value: val, isSet: true}
}

func (v NullableAuthorization202403DeauthorizeShopResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorization202403DeauthorizeShopResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


