/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package logistics_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Logistics202309GetGlobalSellerWarehouseResponseData type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Logistics202309GetGlobalSellerWarehouseResponseData{}

// Logistics202309GetGlobalSellerWarehouseResponseData struct for Logistics202309GetGlobalSellerWarehouseResponseData
type Logistics202309GetGlobalSellerWarehouseResponseData struct {
    // Global warehouse information.
    GlobalWarehouses []Logistics202309GetGlobalSellerWarehouseResponseDataGlobalWarehouses `json:"global_warehouses,omitempty"`
}

// NewLogistics202309GetGlobalSellerWarehouseResponseData instantiates a new Logistics202309GetGlobalSellerWarehouseResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogistics202309GetGlobalSellerWarehouseResponseData() *Logistics202309GetGlobalSellerWarehouseResponseData {
    this := Logistics202309GetGlobalSellerWarehouseResponseData{}
    return &this
}

// NewLogistics202309GetGlobalSellerWarehouseResponseDataWithDefaults instantiates a new Logistics202309GetGlobalSellerWarehouseResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLogistics202309GetGlobalSellerWarehouseResponseDataWithDefaults() *Logistics202309GetGlobalSellerWarehouseResponseData {
    this := Logistics202309GetGlobalSellerWarehouseResponseData{}
    return &this
}

// GetGlobalWarehouses returns the GlobalWarehouses field value if set, zero value otherwise.
func (o *Logistics202309GetGlobalSellerWarehouseResponseData) GetGlobalWarehouses() []Logistics202309GetGlobalSellerWarehouseResponseDataGlobalWarehouses {
    if o == nil || utils.IsNil(o.GlobalWarehouses) {
        var ret []Logistics202309GetGlobalSellerWarehouseResponseDataGlobalWarehouses
        return ret
    }
    return o.GlobalWarehouses
}

// GetGlobalWarehousesOk returns a tuple with the GlobalWarehouses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Logistics202309GetGlobalSellerWarehouseResponseData) GetGlobalWarehousesOk() ([]Logistics202309GetGlobalSellerWarehouseResponseDataGlobalWarehouses, bool) {
    if o == nil || utils.IsNil(o.GlobalWarehouses) {
        return nil, false
    }
    return o.GlobalWarehouses, true
}

// HasGlobalWarehouses returns a boolean if a field has been set.
func (o *Logistics202309GetGlobalSellerWarehouseResponseData) HasGlobalWarehouses() bool {
    if o != nil && !utils.IsNil(o.GlobalWarehouses) {
        return true
    }

    return false
}

// SetGlobalWarehouses gets a reference to the given []Logistics202309GetGlobalSellerWarehouseResponseDataGlobalWarehouses and assigns it to the GlobalWarehouses field.
func (o *Logistics202309GetGlobalSellerWarehouseResponseData) SetGlobalWarehouses(v []Logistics202309GetGlobalSellerWarehouseResponseDataGlobalWarehouses) {
    o.GlobalWarehouses = v
}

func (o Logistics202309GetGlobalSellerWarehouseResponseData) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Logistics202309GetGlobalSellerWarehouseResponseData) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.GlobalWarehouses) {
        toSerialize["global_warehouses"] = o.GlobalWarehouses
    }
    return toSerialize, nil
}

type NullableLogistics202309GetGlobalSellerWarehouseResponseData struct {
	value *Logistics202309GetGlobalSellerWarehouseResponseData
	isSet bool
}

func (v NullableLogistics202309GetGlobalSellerWarehouseResponseData) Get() *Logistics202309GetGlobalSellerWarehouseResponseData {
	return v.value
}

func (v *NullableLogistics202309GetGlobalSellerWarehouseResponseData) Set(val *Logistics202309GetGlobalSellerWarehouseResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableLogistics202309GetGlobalSellerWarehouseResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableLogistics202309GetGlobalSellerWarehouseResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogistics202309GetGlobalSellerWarehouseResponseData(val *Logistics202309GetGlobalSellerWarehouseResponseData) *NullableLogistics202309GetGlobalSellerWarehouseResponseData {
	return &NullableLogistics202309GetGlobalSellerWarehouseResponseData{value: val, isSet: true}
}

func (v NullableLogistics202309GetGlobalSellerWarehouseResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogistics202309GetGlobalSellerWarehouseResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


