/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package seller_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Seller202309GetActiveShopsResponseDataShops type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Seller202309GetActiveShopsResponseDataShops{}

// Seller202309GetActiveShopsResponseDataShops struct for Seller202309GetActiveShopsResponseDataShops
type Seller202309GetActiveShopsResponseDataShops struct {
    // The ID of the shop.
    Id *string `json:"id,omitempty"`
    // The region of the shop.
    Region *string `json:"region,omitempty"`
}

// NewSeller202309GetActiveShopsResponseDataShops instantiates a new Seller202309GetActiveShopsResponseDataShops object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSeller202309GetActiveShopsResponseDataShops() *Seller202309GetActiveShopsResponseDataShops {
    this := Seller202309GetActiveShopsResponseDataShops{}
    return &this
}

// NewSeller202309GetActiveShopsResponseDataShopsWithDefaults instantiates a new Seller202309GetActiveShopsResponseDataShops object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSeller202309GetActiveShopsResponseDataShopsWithDefaults() *Seller202309GetActiveShopsResponseDataShops {
    this := Seller202309GetActiveShopsResponseDataShops{}
    return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Seller202309GetActiveShopsResponseDataShops) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Seller202309GetActiveShopsResponseDataShops) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Seller202309GetActiveShopsResponseDataShops) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Seller202309GetActiveShopsResponseDataShops) SetId(v string) {
    o.Id = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *Seller202309GetActiveShopsResponseDataShops) GetRegion() string {
    if o == nil || utils.IsNil(o.Region) {
        var ret string
        return ret
    }
    return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Seller202309GetActiveShopsResponseDataShops) GetRegionOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Region) {
        return nil, false
    }
    return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *Seller202309GetActiveShopsResponseDataShops) HasRegion() bool {
    if o != nil && !utils.IsNil(o.Region) {
        return true
    }

    return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *Seller202309GetActiveShopsResponseDataShops) SetRegion(v string) {
    o.Region = &v
}

func (o Seller202309GetActiveShopsResponseDataShops) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Seller202309GetActiveShopsResponseDataShops) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }
    if !utils.IsNil(o.Region) {
        toSerialize["region"] = o.Region
    }
    return toSerialize, nil
}

type NullableSeller202309GetActiveShopsResponseDataShops struct {
	value *Seller202309GetActiveShopsResponseDataShops
	isSet bool
}

func (v NullableSeller202309GetActiveShopsResponseDataShops) Get() *Seller202309GetActiveShopsResponseDataShops {
	return v.value
}

func (v *NullableSeller202309GetActiveShopsResponseDataShops) Set(val *Seller202309GetActiveShopsResponseDataShops) {
	v.value = val
	v.isSet = true
}

func (v NullableSeller202309GetActiveShopsResponseDataShops) IsSet() bool {
	return v.isSet
}

func (v *NullableSeller202309GetActiveShopsResponseDataShops) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSeller202309GetActiveShopsResponseDataShops(val *Seller202309GetActiveShopsResponseDataShops) *NullableSeller202309GetActiveShopsResponseDataShops {
	return &NullableSeller202309GetActiveShopsResponseDataShops{value: val, isSet: true}
}

func (v NullableSeller202309GetActiveShopsResponseDataShops) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSeller202309GetActiveShopsResponseDataShops) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


