/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package return_refund_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the ReturnRefund202309ApproveReturnRequestBody type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &ReturnRefund202309ApproveReturnRequestBody{}

// ReturnRefund202309ApproveReturnRequestBody struct for ReturnRefund202309ApproveReturnRequestBody
type ReturnRefund202309ApproveReturnRequestBody struct {
    // If true, the seller will issue a returnless refund. In other words, the seller will refund without requiring the buyer to send the product back to the seller.  Note: Seller's decision for the return request should be APPROVE_RETURN
    BuyerKeepItem *bool `json:"buyer_keep_item,omitempty"`
    // Seller's decision for the return request, available values: - APPROVE_REFUND: seller approve  refund request - APPROVE_RETURN: seller approve return request - APPROVE_RECEIVED_PACKAGE: seller approve received package - APPROVE_REPLACEMENT: seller approve replacement request - ISSUE_REPLACEMENT_REFUND: seller decline the replacement request and directly refund to buyer. - OFFER_PARTIAL_REFUND: seller offer partial refund. Partial refund no need buyer to return the product. If buyer accept partial refund, seller only refund the partial amount and buyer keep the item(s).
    Decision *string `json:"decision,omitempty"`
    PartialRefund *ReturnRefund202309ApproveReturnRequestBodyPartialRefund `json:"partial_refund,omitempty"`
}

// NewReturnRefund202309ApproveReturnRequestBody instantiates a new ReturnRefund202309ApproveReturnRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReturnRefund202309ApproveReturnRequestBody() *ReturnRefund202309ApproveReturnRequestBody {
    this := ReturnRefund202309ApproveReturnRequestBody{}
    return &this
}

// NewReturnRefund202309ApproveReturnRequestBodyWithDefaults instantiates a new ReturnRefund202309ApproveReturnRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReturnRefund202309ApproveReturnRequestBodyWithDefaults() *ReturnRefund202309ApproveReturnRequestBody {
    this := ReturnRefund202309ApproveReturnRequestBody{}
    return &this
}

// GetBuyerKeepItem returns the BuyerKeepItem field value if set, zero value otherwise.
func (o *ReturnRefund202309ApproveReturnRequestBody) GetBuyerKeepItem() bool {
    if o == nil || utils.IsNil(o.BuyerKeepItem) {
        var ret bool
        return ret
    }
    return *o.BuyerKeepItem
}

// GetBuyerKeepItemOk returns a tuple with the BuyerKeepItem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReturnRefund202309ApproveReturnRequestBody) GetBuyerKeepItemOk() (*bool, bool) {
    if o == nil || utils.IsNil(o.BuyerKeepItem) {
        return nil, false
    }
    return o.BuyerKeepItem, true
}

// HasBuyerKeepItem returns a boolean if a field has been set.
func (o *ReturnRefund202309ApproveReturnRequestBody) HasBuyerKeepItem() bool {
    if o != nil && !utils.IsNil(o.BuyerKeepItem) {
        return true
    }

    return false
}

// SetBuyerKeepItem gets a reference to the given bool and assigns it to the BuyerKeepItem field.
func (o *ReturnRefund202309ApproveReturnRequestBody) SetBuyerKeepItem(v bool) {
    o.BuyerKeepItem = &v
}

// GetDecision returns the Decision field value if set, zero value otherwise.
func (o *ReturnRefund202309ApproveReturnRequestBody) GetDecision() string {
    if o == nil || utils.IsNil(o.Decision) {
        var ret string
        return ret
    }
    return *o.Decision
}

// GetDecisionOk returns a tuple with the Decision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReturnRefund202309ApproveReturnRequestBody) GetDecisionOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Decision) {
        return nil, false
    }
    return o.Decision, true
}

// HasDecision returns a boolean if a field has been set.
func (o *ReturnRefund202309ApproveReturnRequestBody) HasDecision() bool {
    if o != nil && !utils.IsNil(o.Decision) {
        return true
    }

    return false
}

// SetDecision gets a reference to the given string and assigns it to the Decision field.
func (o *ReturnRefund202309ApproveReturnRequestBody) SetDecision(v string) {
    o.Decision = &v
}

// GetPartialRefund returns the PartialRefund field value if set, zero value otherwise.
func (o *ReturnRefund202309ApproveReturnRequestBody) GetPartialRefund() ReturnRefund202309ApproveReturnRequestBodyPartialRefund {
    if o == nil || utils.IsNil(o.PartialRefund) {
        var ret ReturnRefund202309ApproveReturnRequestBodyPartialRefund
        return ret
    }
    return *o.PartialRefund
}

// GetPartialRefundOk returns a tuple with the PartialRefund field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReturnRefund202309ApproveReturnRequestBody) GetPartialRefundOk() (*ReturnRefund202309ApproveReturnRequestBodyPartialRefund, bool) {
    if o == nil || utils.IsNil(o.PartialRefund) {
        return nil, false
    }
    return o.PartialRefund, true
}

// HasPartialRefund returns a boolean if a field has been set.
func (o *ReturnRefund202309ApproveReturnRequestBody) HasPartialRefund() bool {
    if o != nil && !utils.IsNil(o.PartialRefund) {
        return true
    }

    return false
}

// SetPartialRefund gets a reference to the given ReturnRefund202309ApproveReturnRequestBodyPartialRefund and assigns it to the PartialRefund field.
func (o *ReturnRefund202309ApproveReturnRequestBody) SetPartialRefund(v ReturnRefund202309ApproveReturnRequestBodyPartialRefund) {
    o.PartialRefund = &v
}

func (o ReturnRefund202309ApproveReturnRequestBody) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o ReturnRefund202309ApproveReturnRequestBody) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.BuyerKeepItem) {
        toSerialize["buyer_keep_item"] = o.BuyerKeepItem
    }
    if !utils.IsNil(o.Decision) {
        toSerialize["decision"] = o.Decision
    }
    if !utils.IsNil(o.PartialRefund) {
        toSerialize["partial_refund"] = o.PartialRefund
    }
    return toSerialize, nil
}

type NullableReturnRefund202309ApproveReturnRequestBody struct {
	value *ReturnRefund202309ApproveReturnRequestBody
	isSet bool
}

func (v NullableReturnRefund202309ApproveReturnRequestBody) Get() *ReturnRefund202309ApproveReturnRequestBody {
	return v.value
}

func (v *NullableReturnRefund202309ApproveReturnRequestBody) Set(val *ReturnRefund202309ApproveReturnRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableReturnRefund202309ApproveReturnRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableReturnRefund202309ApproveReturnRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReturnRefund202309ApproveReturnRequestBody(val *ReturnRefund202309ApproveReturnRequestBody) *NullableReturnRefund202309ApproveReturnRequestBody {
	return &NullableReturnRefund202309ApproveReturnRequestBody{value: val, isSet: true}
}

func (v NullableReturnRefund202309ApproveReturnRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReturnRefund202309ApproveReturnRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


