/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package return_refund_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the ReturnRefund202309CancelOrderRequestBody type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &ReturnRefund202309CancelOrderRequestBody{}

// ReturnRefund202309CancelOrderRequestBody struct for ReturnRefund202309CancelOrderRequestBody
type ReturnRefund202309CancelOrderRequestBody struct {
    // Reason to cancel the order  Please see \"Return API Overview\" for a list of reasons a seller can select to cancel the order. 
    CancelReason *string `json:"cancel_reason,omitempty"`
    // TikTok Shop order id
    OrderId *string `json:"order_id,omitempty"`
    // List of order line item ids to cancel. In the US and UK markets, when an item is out of stock, partial cancellation on the single item level is supported. To initiate a partial cancellation, specify the item's order line id.
    OrderLineItemIds []string `json:"order_line_item_ids,omitempty"`
    // List of SKU to cancel
    Skus []ReturnRefund202309CancelOrderRequestBodySkus `json:"skus,omitempty"`
}

// NewReturnRefund202309CancelOrderRequestBody instantiates a new ReturnRefund202309CancelOrderRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReturnRefund202309CancelOrderRequestBody() *ReturnRefund202309CancelOrderRequestBody {
    this := ReturnRefund202309CancelOrderRequestBody{}
    return &this
}

// NewReturnRefund202309CancelOrderRequestBodyWithDefaults instantiates a new ReturnRefund202309CancelOrderRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReturnRefund202309CancelOrderRequestBodyWithDefaults() *ReturnRefund202309CancelOrderRequestBody {
    this := ReturnRefund202309CancelOrderRequestBody{}
    return &this
}

// GetCancelReason returns the CancelReason field value if set, zero value otherwise.
func (o *ReturnRefund202309CancelOrderRequestBody) GetCancelReason() string {
    if o == nil || utils.IsNil(o.CancelReason) {
        var ret string
        return ret
    }
    return *o.CancelReason
}

// GetCancelReasonOk returns a tuple with the CancelReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReturnRefund202309CancelOrderRequestBody) GetCancelReasonOk() (*string, bool) {
    if o == nil || utils.IsNil(o.CancelReason) {
        return nil, false
    }
    return o.CancelReason, true
}

// HasCancelReason returns a boolean if a field has been set.
func (o *ReturnRefund202309CancelOrderRequestBody) HasCancelReason() bool {
    if o != nil && !utils.IsNil(o.CancelReason) {
        return true
    }

    return false
}

// SetCancelReason gets a reference to the given string and assigns it to the CancelReason field.
func (o *ReturnRefund202309CancelOrderRequestBody) SetCancelReason(v string) {
    o.CancelReason = &v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *ReturnRefund202309CancelOrderRequestBody) GetOrderId() string {
    if o == nil || utils.IsNil(o.OrderId) {
        var ret string
        return ret
    }
    return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReturnRefund202309CancelOrderRequestBody) GetOrderIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.OrderId) {
        return nil, false
    }
    return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *ReturnRefund202309CancelOrderRequestBody) HasOrderId() bool {
    if o != nil && !utils.IsNil(o.OrderId) {
        return true
    }

    return false
}

// SetOrderId gets a reference to the given string and assigns it to the OrderId field.
func (o *ReturnRefund202309CancelOrderRequestBody) SetOrderId(v string) {
    o.OrderId = &v
}

// GetOrderLineItemIds returns the OrderLineItemIds field value if set, zero value otherwise.
func (o *ReturnRefund202309CancelOrderRequestBody) GetOrderLineItemIds() []string {
    if o == nil || utils.IsNil(o.OrderLineItemIds) {
        var ret []string
        return ret
    }
    return o.OrderLineItemIds
}

// GetOrderLineItemIdsOk returns a tuple with the OrderLineItemIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReturnRefund202309CancelOrderRequestBody) GetOrderLineItemIdsOk() ([]string, bool) {
    if o == nil || utils.IsNil(o.OrderLineItemIds) {
        return nil, false
    }
    return o.OrderLineItemIds, true
}

// HasOrderLineItemIds returns a boolean if a field has been set.
func (o *ReturnRefund202309CancelOrderRequestBody) HasOrderLineItemIds() bool {
    if o != nil && !utils.IsNil(o.OrderLineItemIds) {
        return true
    }

    return false
}

// SetOrderLineItemIds gets a reference to the given []string and assigns it to the OrderLineItemIds field.
func (o *ReturnRefund202309CancelOrderRequestBody) SetOrderLineItemIds(v []string) {
    o.OrderLineItemIds = v
}

// GetSkus returns the Skus field value if set, zero value otherwise.
func (o *ReturnRefund202309CancelOrderRequestBody) GetSkus() []ReturnRefund202309CancelOrderRequestBodySkus {
    if o == nil || utils.IsNil(o.Skus) {
        var ret []ReturnRefund202309CancelOrderRequestBodySkus
        return ret
    }
    return o.Skus
}

// GetSkusOk returns a tuple with the Skus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReturnRefund202309CancelOrderRequestBody) GetSkusOk() ([]ReturnRefund202309CancelOrderRequestBodySkus, bool) {
    if o == nil || utils.IsNil(o.Skus) {
        return nil, false
    }
    return o.Skus, true
}

// HasSkus returns a boolean if a field has been set.
func (o *ReturnRefund202309CancelOrderRequestBody) HasSkus() bool {
    if o != nil && !utils.IsNil(o.Skus) {
        return true
    }

    return false
}

// SetSkus gets a reference to the given []ReturnRefund202309CancelOrderRequestBodySkus and assigns it to the Skus field.
func (o *ReturnRefund202309CancelOrderRequestBody) SetSkus(v []ReturnRefund202309CancelOrderRequestBodySkus) {
    o.Skus = v
}

func (o ReturnRefund202309CancelOrderRequestBody) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o ReturnRefund202309CancelOrderRequestBody) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.CancelReason) {
        toSerialize["cancel_reason"] = o.CancelReason
    }
    if !utils.IsNil(o.OrderId) {
        toSerialize["order_id"] = o.OrderId
    }
    if !utils.IsNil(o.OrderLineItemIds) {
        toSerialize["order_line_item_ids"] = o.OrderLineItemIds
    }
    if !utils.IsNil(o.Skus) {
        toSerialize["skus"] = o.Skus
    }
    return toSerialize, nil
}

type NullableReturnRefund202309CancelOrderRequestBody struct {
	value *ReturnRefund202309CancelOrderRequestBody
	isSet bool
}

func (v NullableReturnRefund202309CancelOrderRequestBody) Get() *ReturnRefund202309CancelOrderRequestBody {
	return v.value
}

func (v *NullableReturnRefund202309CancelOrderRequestBody) Set(val *ReturnRefund202309CancelOrderRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableReturnRefund202309CancelOrderRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableReturnRefund202309CancelOrderRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReturnRefund202309CancelOrderRequestBody(val *ReturnRefund202309CancelOrderRequestBody) *NullableReturnRefund202309CancelOrderRequestBody {
	return &NullableReturnRefund202309CancelOrderRequestBody{value: val, isSet: true}
}

func (v NullableReturnRefund202309CancelOrderRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReturnRefund202309CancelOrderRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


