/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package return_refund_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the ReturnRefund202309RejectReturnResponse type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &ReturnRefund202309RejectReturnResponse{}

// ReturnRefund202309RejectReturnResponse struct for ReturnRefund202309RejectReturnResponse
type ReturnRefund202309RejectReturnResponse struct {
    // The success or failure status code returned in API response.
    Code *int32 `json:"code,omitempty"`
    Data map[string]interface{} `json:"data,omitempty"`
    // The success or failure messages returned in API response. Reasons of failure will be described in the message.
    Message *string `json:"message,omitempty"`
    // Request log.
    RequestId *string `json:"request_id,omitempty"`
}

// NewReturnRefund202309RejectReturnResponse instantiates a new ReturnRefund202309RejectReturnResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReturnRefund202309RejectReturnResponse() *ReturnRefund202309RejectReturnResponse {
    this := ReturnRefund202309RejectReturnResponse{}
    return &this
}

// NewReturnRefund202309RejectReturnResponseWithDefaults instantiates a new ReturnRefund202309RejectReturnResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReturnRefund202309RejectReturnResponseWithDefaults() *ReturnRefund202309RejectReturnResponse {
    this := ReturnRefund202309RejectReturnResponse{}
    return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ReturnRefund202309RejectReturnResponse) GetCode() int32 {
    if o == nil || utils.IsNil(o.Code) {
        var ret int32
        return ret
    }
    return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReturnRefund202309RejectReturnResponse) GetCodeOk() (*int32, bool) {
    if o == nil || utils.IsNil(o.Code) {
        return nil, false
    }
    return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ReturnRefund202309RejectReturnResponse) HasCode() bool {
    if o != nil && !utils.IsNil(o.Code) {
        return true
    }

    return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *ReturnRefund202309RejectReturnResponse) SetCode(v int32) {
    o.Code = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ReturnRefund202309RejectReturnResponse) GetData() map[string]interface{} {
    if o == nil || utils.IsNil(o.Data) {
        var ret map[string]interface{}
        return ret
    }
    return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReturnRefund202309RejectReturnResponse) GetDataOk() (map[string]interface{}, bool) {
    if o == nil || utils.IsNil(o.Data) {
        return map[string]interface{}{}, false
    }
    return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ReturnRefund202309RejectReturnResponse) HasData() bool {
    if o != nil && !utils.IsNil(o.Data) {
        return true
    }

    return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *ReturnRefund202309RejectReturnResponse) SetData(v map[string]interface{}) {
    o.Data = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ReturnRefund202309RejectReturnResponse) GetMessage() string {
    if o == nil || utils.IsNil(o.Message) {
        var ret string
        return ret
    }
    return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReturnRefund202309RejectReturnResponse) GetMessageOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Message) {
        return nil, false
    }
    return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ReturnRefund202309RejectReturnResponse) HasMessage() bool {
    if o != nil && !utils.IsNil(o.Message) {
        return true
    }

    return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ReturnRefund202309RejectReturnResponse) SetMessage(v string) {
    o.Message = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *ReturnRefund202309RejectReturnResponse) GetRequestId() string {
    if o == nil || utils.IsNil(o.RequestId) {
        var ret string
        return ret
    }
    return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReturnRefund202309RejectReturnResponse) GetRequestIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.RequestId) {
        return nil, false
    }
    return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *ReturnRefund202309RejectReturnResponse) HasRequestId() bool {
    if o != nil && !utils.IsNil(o.RequestId) {
        return true
    }

    return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *ReturnRefund202309RejectReturnResponse) SetRequestId(v string) {
    o.RequestId = &v
}

func (o ReturnRefund202309RejectReturnResponse) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o ReturnRefund202309RejectReturnResponse) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Code) {
        toSerialize["code"] = o.Code
    }
    if !utils.IsNil(o.Data) {
        toSerialize["data"] = o.Data
    }
    if !utils.IsNil(o.Message) {
        toSerialize["message"] = o.Message
    }
    if !utils.IsNil(o.RequestId) {
        toSerialize["request_id"] = o.RequestId
    }
    return toSerialize, nil
}

type NullableReturnRefund202309RejectReturnResponse struct {
	value *ReturnRefund202309RejectReturnResponse
	isSet bool
}

func (v NullableReturnRefund202309RejectReturnResponse) Get() *ReturnRefund202309RejectReturnResponse {
	return v.value
}

func (v *NullableReturnRefund202309RejectReturnResponse) Set(val *ReturnRefund202309RejectReturnResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableReturnRefund202309RejectReturnResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableReturnRefund202309RejectReturnResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReturnRefund202309RejectReturnResponse(val *ReturnRefund202309RejectReturnResponse) *NullableReturnRefund202309RejectReturnResponse {
	return &NullableReturnRefund202309RejectReturnResponse{value: val, isSet: true}
}

func (v NullableReturnRefund202309RejectReturnResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReturnRefund202309RejectReturnResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


