/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package return_refund_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the ReturnRefund202309RejectReturnRequestBodyImages type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &ReturnRefund202309RejectReturnRequestBodyImages{}

// ReturnRefund202309RejectReturnRequestBodyImages struct for ReturnRefund202309RejectReturnRequestBodyImages
type ReturnRefund202309RejectReturnRequestBodyImages struct {
    // Image height Units: px
    Height *int32 `json:"height,omitempty"`
    // Image URI obtained from the [Upload Product Image](https://partner.tiktokshop.com/docv2/page/6509df95defece02be598a22) API.
    ImageId *string `json:"image_id,omitempty"`
    // MIME type.
    MimeType *string `json:"mime_type,omitempty"`
    // Image width Units: px
    Width *int32 `json:"width,omitempty"`
}

// NewReturnRefund202309RejectReturnRequestBodyImages instantiates a new ReturnRefund202309RejectReturnRequestBodyImages object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReturnRefund202309RejectReturnRequestBodyImages() *ReturnRefund202309RejectReturnRequestBodyImages {
    this := ReturnRefund202309RejectReturnRequestBodyImages{}
    return &this
}

// NewReturnRefund202309RejectReturnRequestBodyImagesWithDefaults instantiates a new ReturnRefund202309RejectReturnRequestBodyImages object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReturnRefund202309RejectReturnRequestBodyImagesWithDefaults() *ReturnRefund202309RejectReturnRequestBodyImages {
    this := ReturnRefund202309RejectReturnRequestBodyImages{}
    return &this
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *ReturnRefund202309RejectReturnRequestBodyImages) GetHeight() int32 {
    if o == nil || utils.IsNil(o.Height) {
        var ret int32
        return ret
    }
    return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReturnRefund202309RejectReturnRequestBodyImages) GetHeightOk() (*int32, bool) {
    if o == nil || utils.IsNil(o.Height) {
        return nil, false
    }
    return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *ReturnRefund202309RejectReturnRequestBodyImages) HasHeight() bool {
    if o != nil && !utils.IsNil(o.Height) {
        return true
    }

    return false
}

// SetHeight gets a reference to the given int32 and assigns it to the Height field.
func (o *ReturnRefund202309RejectReturnRequestBodyImages) SetHeight(v int32) {
    o.Height = &v
}

// GetImageId returns the ImageId field value if set, zero value otherwise.
func (o *ReturnRefund202309RejectReturnRequestBodyImages) GetImageId() string {
    if o == nil || utils.IsNil(o.ImageId) {
        var ret string
        return ret
    }
    return *o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReturnRefund202309RejectReturnRequestBodyImages) GetImageIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.ImageId) {
        return nil, false
    }
    return o.ImageId, true
}

// HasImageId returns a boolean if a field has been set.
func (o *ReturnRefund202309RejectReturnRequestBodyImages) HasImageId() bool {
    if o != nil && !utils.IsNil(o.ImageId) {
        return true
    }

    return false
}

// SetImageId gets a reference to the given string and assigns it to the ImageId field.
func (o *ReturnRefund202309RejectReturnRequestBodyImages) SetImageId(v string) {
    o.ImageId = &v
}

// GetMimeType returns the MimeType field value if set, zero value otherwise.
func (o *ReturnRefund202309RejectReturnRequestBodyImages) GetMimeType() string {
    if o == nil || utils.IsNil(o.MimeType) {
        var ret string
        return ret
    }
    return *o.MimeType
}

// GetMimeTypeOk returns a tuple with the MimeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReturnRefund202309RejectReturnRequestBodyImages) GetMimeTypeOk() (*string, bool) {
    if o == nil || utils.IsNil(o.MimeType) {
        return nil, false
    }
    return o.MimeType, true
}

// HasMimeType returns a boolean if a field has been set.
func (o *ReturnRefund202309RejectReturnRequestBodyImages) HasMimeType() bool {
    if o != nil && !utils.IsNil(o.MimeType) {
        return true
    }

    return false
}

// SetMimeType gets a reference to the given string and assigns it to the MimeType field.
func (o *ReturnRefund202309RejectReturnRequestBodyImages) SetMimeType(v string) {
    o.MimeType = &v
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *ReturnRefund202309RejectReturnRequestBodyImages) GetWidth() int32 {
    if o == nil || utils.IsNil(o.Width) {
        var ret int32
        return ret
    }
    return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReturnRefund202309RejectReturnRequestBodyImages) GetWidthOk() (*int32, bool) {
    if o == nil || utils.IsNil(o.Width) {
        return nil, false
    }
    return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *ReturnRefund202309RejectReturnRequestBodyImages) HasWidth() bool {
    if o != nil && !utils.IsNil(o.Width) {
        return true
    }

    return false
}

// SetWidth gets a reference to the given int32 and assigns it to the Width field.
func (o *ReturnRefund202309RejectReturnRequestBodyImages) SetWidth(v int32) {
    o.Width = &v
}

func (o ReturnRefund202309RejectReturnRequestBodyImages) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o ReturnRefund202309RejectReturnRequestBodyImages) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Height) {
        toSerialize["height"] = o.Height
    }
    if !utils.IsNil(o.ImageId) {
        toSerialize["image_id"] = o.ImageId
    }
    if !utils.IsNil(o.MimeType) {
        toSerialize["mime_type"] = o.MimeType
    }
    if !utils.IsNil(o.Width) {
        toSerialize["width"] = o.Width
    }
    return toSerialize, nil
}

type NullableReturnRefund202309RejectReturnRequestBodyImages struct {
	value *ReturnRefund202309RejectReturnRequestBodyImages
	isSet bool
}

func (v NullableReturnRefund202309RejectReturnRequestBodyImages) Get() *ReturnRefund202309RejectReturnRequestBodyImages {
	return v.value
}

func (v *NullableReturnRefund202309RejectReturnRequestBodyImages) Set(val *ReturnRefund202309RejectReturnRequestBodyImages) {
	v.value = val
	v.isSet = true
}

func (v NullableReturnRefund202309RejectReturnRequestBodyImages) IsSet() bool {
	return v.isSet
}

func (v *NullableReturnRefund202309RejectReturnRequestBodyImages) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReturnRefund202309RejectReturnRequestBodyImages(val *ReturnRefund202309RejectReturnRequestBodyImages) *NullableReturnRefund202309RejectReturnRequestBodyImages {
	return &NullableReturnRefund202309RejectReturnRequestBodyImages{value: val, isSet: true}
}

func (v NullableReturnRefund202309RejectReturnRequestBodyImages) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReturnRefund202309RejectReturnRequestBodyImages) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


