/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package return_refund_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse{}

// ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse struct for ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse
type ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse struct {
    // Seller's next action. Possible values: - SELLER_RESPOND_CANCEL
    Action *string `json:"action,omitempty"`
    // Unix timestamp indicating the deadline for when the seller must perform the next action.
    Deadline *int64 `json:"deadline,omitempty"`
}

// NewReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse instantiates a new ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse() *ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse {
    this := ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse{}
    return &this
}

// NewReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponseWithDefaults instantiates a new ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponseWithDefaults() *ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse {
    this := ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse{}
    return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse) GetAction() string {
    if o == nil || utils.IsNil(o.Action) {
        var ret string
        return ret
    }
    return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse) GetActionOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Action) {
        return nil, false
    }
    return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse) HasAction() bool {
    if o != nil && !utils.IsNil(o.Action) {
        return true
    }

    return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse) SetAction(v string) {
    o.Action = &v
}

// GetDeadline returns the Deadline field value if set, zero value otherwise.
func (o *ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse) GetDeadline() int64 {
    if o == nil || utils.IsNil(o.Deadline) {
        var ret int64
        return ret
    }
    return *o.Deadline
}

// GetDeadlineOk returns a tuple with the Deadline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse) GetDeadlineOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.Deadline) {
        return nil, false
    }
    return o.Deadline, true
}

// HasDeadline returns a boolean if a field has been set.
func (o *ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse) HasDeadline() bool {
    if o != nil && !utils.IsNil(o.Deadline) {
        return true
    }

    return false
}

// SetDeadline gets a reference to the given int64 and assigns it to the Deadline field.
func (o *ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse) SetDeadline(v int64) {
    o.Deadline = &v
}

func (o ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Action) {
        toSerialize["action"] = o.Action
    }
    if !utils.IsNil(o.Deadline) {
        toSerialize["deadline"] = o.Deadline
    }
    return toSerialize, nil
}

type NullableReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse struct {
	value *ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse
	isSet bool
}

func (v NullableReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse) Get() *ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse {
	return v.value
}

func (v *NullableReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse) Set(val *ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse(val *ReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse) *NullableReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse {
	return &NullableReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse{value: val, isSet: true}
}

func (v NullableReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReturnRefund202309SearchCancellationsResponseDataCancellationsSellerNextActionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


