/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Promotion202309DeactivateActivityResponseData type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Promotion202309DeactivateActivityResponseData{}

// Promotion202309DeactivateActivityResponseData struct for Promotion202309DeactivateActivityResponseData
type Promotion202309DeactivateActivityResponseData struct {
    // A unique ID that identifies different activities.
    ActivityId *string `json:"activity_id,omitempty"`
    // Activity status. Values: - DRAFT: Promotion activities with this status are not available to TikTok users. - NOT_START: Promotion activities with this status are not available to TikTok users until the the set activity start time. - ONGOING: Promotion activities with this status are available to TikTok users. - EXPIRED: Promotion activities with this status are not available to TikTok users because it has expired. - DEACTIVATED: The activity has been deactivated by the seller and is not available to TikTok users. - NOT_EFFECTIVE:  The activity is not in effect and is not available to TikTok users.
    Status *string `json:"status,omitempty"`
    // Activity name (50 characters max.) The name must be unique.
    Title *string `json:"title,omitempty"`
    // Activity update time, unix timestamp.
    UpdateTime *int64 `json:"update_time,omitempty"`
}

// NewPromotion202309DeactivateActivityResponseData instantiates a new Promotion202309DeactivateActivityResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromotion202309DeactivateActivityResponseData() *Promotion202309DeactivateActivityResponseData {
    this := Promotion202309DeactivateActivityResponseData{}
    return &this
}

// NewPromotion202309DeactivateActivityResponseDataWithDefaults instantiates a new Promotion202309DeactivateActivityResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromotion202309DeactivateActivityResponseDataWithDefaults() *Promotion202309DeactivateActivityResponseData {
    this := Promotion202309DeactivateActivityResponseData{}
    return &this
}

// GetActivityId returns the ActivityId field value if set, zero value otherwise.
func (o *Promotion202309DeactivateActivityResponseData) GetActivityId() string {
    if o == nil || utils.IsNil(o.ActivityId) {
        var ret string
        return ret
    }
    return *o.ActivityId
}

// GetActivityIdOk returns a tuple with the ActivityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Promotion202309DeactivateActivityResponseData) GetActivityIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.ActivityId) {
        return nil, false
    }
    return o.ActivityId, true
}

// HasActivityId returns a boolean if a field has been set.
func (o *Promotion202309DeactivateActivityResponseData) HasActivityId() bool {
    if o != nil && !utils.IsNil(o.ActivityId) {
        return true
    }

    return false
}

// SetActivityId gets a reference to the given string and assigns it to the ActivityId field.
func (o *Promotion202309DeactivateActivityResponseData) SetActivityId(v string) {
    o.ActivityId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Promotion202309DeactivateActivityResponseData) GetStatus() string {
    if o == nil || utils.IsNil(o.Status) {
        var ret string
        return ret
    }
    return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Promotion202309DeactivateActivityResponseData) GetStatusOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Status) {
        return nil, false
    }
    return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Promotion202309DeactivateActivityResponseData) HasStatus() bool {
    if o != nil && !utils.IsNil(o.Status) {
        return true
    }

    return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *Promotion202309DeactivateActivityResponseData) SetStatus(v string) {
    o.Status = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *Promotion202309DeactivateActivityResponseData) GetTitle() string {
    if o == nil || utils.IsNil(o.Title) {
        var ret string
        return ret
    }
    return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Promotion202309DeactivateActivityResponseData) GetTitleOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Title) {
        return nil, false
    }
    return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *Promotion202309DeactivateActivityResponseData) HasTitle() bool {
    if o != nil && !utils.IsNil(o.Title) {
        return true
    }

    return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *Promotion202309DeactivateActivityResponseData) SetTitle(v string) {
    o.Title = &v
}

// GetUpdateTime returns the UpdateTime field value if set, zero value otherwise.
func (o *Promotion202309DeactivateActivityResponseData) GetUpdateTime() int64 {
    if o == nil || utils.IsNil(o.UpdateTime) {
        var ret int64
        return ret
    }
    return *o.UpdateTime
}

// GetUpdateTimeOk returns a tuple with the UpdateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Promotion202309DeactivateActivityResponseData) GetUpdateTimeOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.UpdateTime) {
        return nil, false
    }
    return o.UpdateTime, true
}

// HasUpdateTime returns a boolean if a field has been set.
func (o *Promotion202309DeactivateActivityResponseData) HasUpdateTime() bool {
    if o != nil && !utils.IsNil(o.UpdateTime) {
        return true
    }

    return false
}

// SetUpdateTime gets a reference to the given int64 and assigns it to the UpdateTime field.
func (o *Promotion202309DeactivateActivityResponseData) SetUpdateTime(v int64) {
    o.UpdateTime = &v
}

func (o Promotion202309DeactivateActivityResponseData) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Promotion202309DeactivateActivityResponseData) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.ActivityId) {
        toSerialize["activity_id"] = o.ActivityId
    }
    if !utils.IsNil(o.Status) {
        toSerialize["status"] = o.Status
    }
    if !utils.IsNil(o.Title) {
        toSerialize["title"] = o.Title
    }
    if !utils.IsNil(o.UpdateTime) {
        toSerialize["update_time"] = o.UpdateTime
    }
    return toSerialize, nil
}

type NullablePromotion202309DeactivateActivityResponseData struct {
	value *Promotion202309DeactivateActivityResponseData
	isSet bool
}

func (v NullablePromotion202309DeactivateActivityResponseData) Get() *Promotion202309DeactivateActivityResponseData {
	return v.value
}

func (v *NullablePromotion202309DeactivateActivityResponseData) Set(val *Promotion202309DeactivateActivityResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullablePromotion202309DeactivateActivityResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullablePromotion202309DeactivateActivityResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromotion202309DeactivateActivityResponseData(val *Promotion202309DeactivateActivityResponseData) *NullablePromotion202309DeactivateActivityResponseData {
	return &NullablePromotion202309DeactivateActivityResponseData{value: val, isSet: true}
}

func (v NullablePromotion202309DeactivateActivityResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromotion202309DeactivateActivityResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


