/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Promotion202309SearchActivitiesResponseDataActivities type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Promotion202309SearchActivitiesResponseDataActivities{}

// Promotion202309SearchActivitiesResponseDataActivities struct for Promotion202309SearchActivitiesResponseDataActivities
type Promotion202309SearchActivitiesResponseDataActivities struct {
    // Applicable commands to the activity:  - IMMUTABLE: The activity cannot be edited or deactivated.
    ActivityCommands []string `json:"activity_commands,omitempty"`
    // The type of activities. Possible values: - `FIXED_PRICE` - `DIRECT_DISCOUNT` - `FLASHSALE` - `SHIPPING_DISCOUNT`
    ActivityType *string `json:"activity_type,omitempty"`
    // Activity start time. UNIX timestamp. The value must be greater than the value of the current time.
    BeginTime *int64 `json:"begin_time,omitempty"`
    // The time when the activity was created.
    CreateTime *int64 `json:"create_time,omitempty"`
    Discount *Promotion202309SearchActivitiesResponseDataActivitiesDiscount `json:"discount,omitempty"`
    // The effective time type of the current activity - NORMAL:  `begin_time` and `end_time` must be filled - INDEFINITE: `begin_time` and `end_time` aren't required, and the promotion will be a long-term activity which runs indefinitely.  1.  `INDEFINITE` is only valid when `activity_type` is `SHIPPING_DISCOUNT`, 2. If `duration_type` is `INDEFINITE`, `start_time` and `end_time` should be 0 Default: NORMAL
    DurationType *string `json:"duration_type,omitempty"`
    // Activity end time. UNIX timestamp.
    EndTime *int64 `json:"end_time,omitempty"`
    // A unique ID that identifies different activities.
    Id *string `json:"id,omitempty"`
    // The number of times a buyer can participate in the promotion.
    ParticipationLimit []Promotion202309SearchActivitiesResponseDataActivitiesParticipationLimit `json:"participation_limit,omitempty"`
    // Activity product dimension, values are: ​- PRODUCT: Promotion activity applies at the product (SPU) level. Any and all SKUs that are part of this product will be subject to the promotion. ​- VARIATION: Promotion activity only applies to specified SKUs. ​- SHOP: Promotion activity applies to all products in the shop.
    ProductLevel *string `json:"product_level,omitempty"`
    // Activity status. Possible values: - DRAFT: Promotion activities with this status are not available to TikTok users. - NOT_START: Promotion activities with this status are not available to TikTok users until the set activity start time. - ONGOING: Promotion activities with this status are available to TikTok users. - EXPIRED: Promotion activities with this status are not available to TikTok users because it has expired. - DEACTIVATED: The activity has been deactivated by the seller and is not available to TikTok users. - NOT_EFFECTIVE:  The activity is terminated by the platform and is not available to TikTok users.
    Status *string `json:"status,omitempty"`
    // Activity name (50 characters max).
    Title *string `json:"title,omitempty"`
    // The time when the activity was last updated.
    UpdateTime *int64 `json:"update_time,omitempty"`
}

// NewPromotion202309SearchActivitiesResponseDataActivities instantiates a new Promotion202309SearchActivitiesResponseDataActivities object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromotion202309SearchActivitiesResponseDataActivities() *Promotion202309SearchActivitiesResponseDataActivities {
    this := Promotion202309SearchActivitiesResponseDataActivities{}
    return &this
}

// NewPromotion202309SearchActivitiesResponseDataActivitiesWithDefaults instantiates a new Promotion202309SearchActivitiesResponseDataActivities object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromotion202309SearchActivitiesResponseDataActivitiesWithDefaults() *Promotion202309SearchActivitiesResponseDataActivities {
    this := Promotion202309SearchActivitiesResponseDataActivities{}
    return &this
}

// GetActivityCommands returns the ActivityCommands field value if set, zero value otherwise.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetActivityCommands() []string {
    if o == nil || utils.IsNil(o.ActivityCommands) {
        var ret []string
        return ret
    }
    return o.ActivityCommands
}

// GetActivityCommandsOk returns a tuple with the ActivityCommands field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetActivityCommandsOk() ([]string, bool) {
    if o == nil || utils.IsNil(o.ActivityCommands) {
        return nil, false
    }
    return o.ActivityCommands, true
}

// HasActivityCommands returns a boolean if a field has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) HasActivityCommands() bool {
    if o != nil && !utils.IsNil(o.ActivityCommands) {
        return true
    }

    return false
}

// SetActivityCommands gets a reference to the given []string and assigns it to the ActivityCommands field.
func (o *Promotion202309SearchActivitiesResponseDataActivities) SetActivityCommands(v []string) {
    o.ActivityCommands = v
}

// GetActivityType returns the ActivityType field value if set, zero value otherwise.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetActivityType() string {
    if o == nil || utils.IsNil(o.ActivityType) {
        var ret string
        return ret
    }
    return *o.ActivityType
}

// GetActivityTypeOk returns a tuple with the ActivityType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetActivityTypeOk() (*string, bool) {
    if o == nil || utils.IsNil(o.ActivityType) {
        return nil, false
    }
    return o.ActivityType, true
}

// HasActivityType returns a boolean if a field has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) HasActivityType() bool {
    if o != nil && !utils.IsNil(o.ActivityType) {
        return true
    }

    return false
}

// SetActivityType gets a reference to the given string and assigns it to the ActivityType field.
func (o *Promotion202309SearchActivitiesResponseDataActivities) SetActivityType(v string) {
    o.ActivityType = &v
}

// GetBeginTime returns the BeginTime field value if set, zero value otherwise.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetBeginTime() int64 {
    if o == nil || utils.IsNil(o.BeginTime) {
        var ret int64
        return ret
    }
    return *o.BeginTime
}

// GetBeginTimeOk returns a tuple with the BeginTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetBeginTimeOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.BeginTime) {
        return nil, false
    }
    return o.BeginTime, true
}

// HasBeginTime returns a boolean if a field has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) HasBeginTime() bool {
    if o != nil && !utils.IsNil(o.BeginTime) {
        return true
    }

    return false
}

// SetBeginTime gets a reference to the given int64 and assigns it to the BeginTime field.
func (o *Promotion202309SearchActivitiesResponseDataActivities) SetBeginTime(v int64) {
    o.BeginTime = &v
}

// GetCreateTime returns the CreateTime field value if set, zero value otherwise.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetCreateTime() int64 {
    if o == nil || utils.IsNil(o.CreateTime) {
        var ret int64
        return ret
    }
    return *o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetCreateTimeOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.CreateTime) {
        return nil, false
    }
    return o.CreateTime, true
}

// HasCreateTime returns a boolean if a field has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) HasCreateTime() bool {
    if o != nil && !utils.IsNil(o.CreateTime) {
        return true
    }

    return false
}

// SetCreateTime gets a reference to the given int64 and assigns it to the CreateTime field.
func (o *Promotion202309SearchActivitiesResponseDataActivities) SetCreateTime(v int64) {
    o.CreateTime = &v
}

// GetDiscount returns the Discount field value if set, zero value otherwise.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetDiscount() Promotion202309SearchActivitiesResponseDataActivitiesDiscount {
    if o == nil || utils.IsNil(o.Discount) {
        var ret Promotion202309SearchActivitiesResponseDataActivitiesDiscount
        return ret
    }
    return *o.Discount
}

// GetDiscountOk returns a tuple with the Discount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetDiscountOk() (*Promotion202309SearchActivitiesResponseDataActivitiesDiscount, bool) {
    if o == nil || utils.IsNil(o.Discount) {
        return nil, false
    }
    return o.Discount, true
}

// HasDiscount returns a boolean if a field has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) HasDiscount() bool {
    if o != nil && !utils.IsNil(o.Discount) {
        return true
    }

    return false
}

// SetDiscount gets a reference to the given Promotion202309SearchActivitiesResponseDataActivitiesDiscount and assigns it to the Discount field.
func (o *Promotion202309SearchActivitiesResponseDataActivities) SetDiscount(v Promotion202309SearchActivitiesResponseDataActivitiesDiscount) {
    o.Discount = &v
}

// GetDurationType returns the DurationType field value if set, zero value otherwise.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetDurationType() string {
    if o == nil || utils.IsNil(o.DurationType) {
        var ret string
        return ret
    }
    return *o.DurationType
}

// GetDurationTypeOk returns a tuple with the DurationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetDurationTypeOk() (*string, bool) {
    if o == nil || utils.IsNil(o.DurationType) {
        return nil, false
    }
    return o.DurationType, true
}

// HasDurationType returns a boolean if a field has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) HasDurationType() bool {
    if o != nil && !utils.IsNil(o.DurationType) {
        return true
    }

    return false
}

// SetDurationType gets a reference to the given string and assigns it to the DurationType field.
func (o *Promotion202309SearchActivitiesResponseDataActivities) SetDurationType(v string) {
    o.DurationType = &v
}

// GetEndTime returns the EndTime field value if set, zero value otherwise.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetEndTime() int64 {
    if o == nil || utils.IsNil(o.EndTime) {
        var ret int64
        return ret
    }
    return *o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetEndTimeOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.EndTime) {
        return nil, false
    }
    return o.EndTime, true
}

// HasEndTime returns a boolean if a field has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) HasEndTime() bool {
    if o != nil && !utils.IsNil(o.EndTime) {
        return true
    }

    return false
}

// SetEndTime gets a reference to the given int64 and assigns it to the EndTime field.
func (o *Promotion202309SearchActivitiesResponseDataActivities) SetEndTime(v int64) {
    o.EndTime = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetId() string {
    if o == nil || utils.IsNil(o.Id) {
        var ret string
        return ret
    }
    return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Id) {
        return nil, false
    }
    return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) HasId() bool {
    if o != nil && !utils.IsNil(o.Id) {
        return true
    }

    return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Promotion202309SearchActivitiesResponseDataActivities) SetId(v string) {
    o.Id = &v
}

// GetParticipationLimit returns the ParticipationLimit field value if set, zero value otherwise.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetParticipationLimit() []Promotion202309SearchActivitiesResponseDataActivitiesParticipationLimit {
    if o == nil || utils.IsNil(o.ParticipationLimit) {
        var ret []Promotion202309SearchActivitiesResponseDataActivitiesParticipationLimit
        return ret
    }
    return o.ParticipationLimit
}

// GetParticipationLimitOk returns a tuple with the ParticipationLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetParticipationLimitOk() ([]Promotion202309SearchActivitiesResponseDataActivitiesParticipationLimit, bool) {
    if o == nil || utils.IsNil(o.ParticipationLimit) {
        return nil, false
    }
    return o.ParticipationLimit, true
}

// HasParticipationLimit returns a boolean if a field has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) HasParticipationLimit() bool {
    if o != nil && !utils.IsNil(o.ParticipationLimit) {
        return true
    }

    return false
}

// SetParticipationLimit gets a reference to the given []Promotion202309SearchActivitiesResponseDataActivitiesParticipationLimit and assigns it to the ParticipationLimit field.
func (o *Promotion202309SearchActivitiesResponseDataActivities) SetParticipationLimit(v []Promotion202309SearchActivitiesResponseDataActivitiesParticipationLimit) {
    o.ParticipationLimit = v
}

// GetProductLevel returns the ProductLevel field value if set, zero value otherwise.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetProductLevel() string {
    if o == nil || utils.IsNil(o.ProductLevel) {
        var ret string
        return ret
    }
    return *o.ProductLevel
}

// GetProductLevelOk returns a tuple with the ProductLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetProductLevelOk() (*string, bool) {
    if o == nil || utils.IsNil(o.ProductLevel) {
        return nil, false
    }
    return o.ProductLevel, true
}

// HasProductLevel returns a boolean if a field has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) HasProductLevel() bool {
    if o != nil && !utils.IsNil(o.ProductLevel) {
        return true
    }

    return false
}

// SetProductLevel gets a reference to the given string and assigns it to the ProductLevel field.
func (o *Promotion202309SearchActivitiesResponseDataActivities) SetProductLevel(v string) {
    o.ProductLevel = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetStatus() string {
    if o == nil || utils.IsNil(o.Status) {
        var ret string
        return ret
    }
    return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetStatusOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Status) {
        return nil, false
    }
    return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) HasStatus() bool {
    if o != nil && !utils.IsNil(o.Status) {
        return true
    }

    return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *Promotion202309SearchActivitiesResponseDataActivities) SetStatus(v string) {
    o.Status = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetTitle() string {
    if o == nil || utils.IsNil(o.Title) {
        var ret string
        return ret
    }
    return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetTitleOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Title) {
        return nil, false
    }
    return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) HasTitle() bool {
    if o != nil && !utils.IsNil(o.Title) {
        return true
    }

    return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *Promotion202309SearchActivitiesResponseDataActivities) SetTitle(v string) {
    o.Title = &v
}

// GetUpdateTime returns the UpdateTime field value if set, zero value otherwise.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetUpdateTime() int64 {
    if o == nil || utils.IsNil(o.UpdateTime) {
        var ret int64
        return ret
    }
    return *o.UpdateTime
}

// GetUpdateTimeOk returns a tuple with the UpdateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) GetUpdateTimeOk() (*int64, bool) {
    if o == nil || utils.IsNil(o.UpdateTime) {
        return nil, false
    }
    return o.UpdateTime, true
}

// HasUpdateTime returns a boolean if a field has been set.
func (o *Promotion202309SearchActivitiesResponseDataActivities) HasUpdateTime() bool {
    if o != nil && !utils.IsNil(o.UpdateTime) {
        return true
    }

    return false
}

// SetUpdateTime gets a reference to the given int64 and assigns it to the UpdateTime field.
func (o *Promotion202309SearchActivitiesResponseDataActivities) SetUpdateTime(v int64) {
    o.UpdateTime = &v
}

func (o Promotion202309SearchActivitiesResponseDataActivities) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Promotion202309SearchActivitiesResponseDataActivities) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.ActivityCommands) {
        toSerialize["activity_commands"] = o.ActivityCommands
    }
    if !utils.IsNil(o.ActivityType) {
        toSerialize["activity_type"] = o.ActivityType
    }
    if !utils.IsNil(o.BeginTime) {
        toSerialize["begin_time"] = o.BeginTime
    }
    if !utils.IsNil(o.CreateTime) {
        toSerialize["create_time"] = o.CreateTime
    }
    if !utils.IsNil(o.Discount) {
        toSerialize["discount"] = o.Discount
    }
    if !utils.IsNil(o.DurationType) {
        toSerialize["duration_type"] = o.DurationType
    }
    if !utils.IsNil(o.EndTime) {
        toSerialize["end_time"] = o.EndTime
    }
    if !utils.IsNil(o.Id) {
        toSerialize["id"] = o.Id
    }
    if !utils.IsNil(o.ParticipationLimit) {
        toSerialize["participation_limit"] = o.ParticipationLimit
    }
    if !utils.IsNil(o.ProductLevel) {
        toSerialize["product_level"] = o.ProductLevel
    }
    if !utils.IsNil(o.Status) {
        toSerialize["status"] = o.Status
    }
    if !utils.IsNil(o.Title) {
        toSerialize["title"] = o.Title
    }
    if !utils.IsNil(o.UpdateTime) {
        toSerialize["update_time"] = o.UpdateTime
    }
    return toSerialize, nil
}

type NullablePromotion202309SearchActivitiesResponseDataActivities struct {
	value *Promotion202309SearchActivitiesResponseDataActivities
	isSet bool
}

func (v NullablePromotion202309SearchActivitiesResponseDataActivities) Get() *Promotion202309SearchActivitiesResponseDataActivities {
	return v.value
}

func (v *NullablePromotion202309SearchActivitiesResponseDataActivities) Set(val *Promotion202309SearchActivitiesResponseDataActivities) {
	v.value = val
	v.isSet = true
}

func (v NullablePromotion202309SearchActivitiesResponseDataActivities) IsSet() bool {
	return v.isSet
}

func (v *NullablePromotion202309SearchActivitiesResponseDataActivities) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromotion202309SearchActivitiesResponseDataActivities(val *Promotion202309SearchActivitiesResponseDataActivities) *NullablePromotion202309SearchActivitiesResponseDataActivities {
	return &NullablePromotion202309SearchActivitiesResponseDataActivities{value: val, isSet: true}
}

func (v NullablePromotion202309SearchActivitiesResponseDataActivities) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromotion202309SearchActivitiesResponseDataActivities) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


