/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails{}

// Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails struct for Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails
type Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails struct {
    // TikTok Shop product id of gift.
    ProductId *string `json:"product_id,omitempty"`
    // TikTok Shop sku id of gift.
    SkuId *string `json:"sku_id,omitempty"`
    // The quantity limit of the gift sku which is involved in the activity. The range is [1, 99999].  If you are updating the value of an existing sku, the value cannot be decreased.
    TotalClaimLimit *string `json:"total_claim_limit,omitempty"`
}

// NewPromotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails instantiates a new Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails() *Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails {
    this := Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails{}
    return &this
}

// NewPromotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetailsWithDefaults instantiates a new Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetailsWithDefaults() *Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails {
    this := Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails{}
    return &this
}

// GetProductId returns the ProductId field value if set, zero value otherwise.
func (o *Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails) GetProductId() string {
    if o == nil || utils.IsNil(o.ProductId) {
        var ret string
        return ret
    }
    return *o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails) GetProductIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.ProductId) {
        return nil, false
    }
    return o.ProductId, true
}

// HasProductId returns a boolean if a field has been set.
func (o *Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails) HasProductId() bool {
    if o != nil && !utils.IsNil(o.ProductId) {
        return true
    }

    return false
}

// SetProductId gets a reference to the given string and assigns it to the ProductId field.
func (o *Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails) SetProductId(v string) {
    o.ProductId = &v
}

// GetSkuId returns the SkuId field value if set, zero value otherwise.
func (o *Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails) GetSkuId() string {
    if o == nil || utils.IsNil(o.SkuId) {
        var ret string
        return ret
    }
    return *o.SkuId
}

// GetSkuIdOk returns a tuple with the SkuId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails) GetSkuIdOk() (*string, bool) {
    if o == nil || utils.IsNil(o.SkuId) {
        return nil, false
    }
    return o.SkuId, true
}

// HasSkuId returns a boolean if a field has been set.
func (o *Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails) HasSkuId() bool {
    if o != nil && !utils.IsNil(o.SkuId) {
        return true
    }

    return false
}

// SetSkuId gets a reference to the given string and assigns it to the SkuId field.
func (o *Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails) SetSkuId(v string) {
    o.SkuId = &v
}

// GetTotalClaimLimit returns the TotalClaimLimit field value if set, zero value otherwise.
func (o *Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails) GetTotalClaimLimit() string {
    if o == nil || utils.IsNil(o.TotalClaimLimit) {
        var ret string
        return ret
    }
    return *o.TotalClaimLimit
}

// GetTotalClaimLimitOk returns a tuple with the TotalClaimLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails) GetTotalClaimLimitOk() (*string, bool) {
    if o == nil || utils.IsNil(o.TotalClaimLimit) {
        return nil, false
    }
    return o.TotalClaimLimit, true
}

// HasTotalClaimLimit returns a boolean if a field has been set.
func (o *Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails) HasTotalClaimLimit() bool {
    if o != nil && !utils.IsNil(o.TotalClaimLimit) {
        return true
    }

    return false
}

// SetTotalClaimLimit gets a reference to the given string and assigns it to the TotalClaimLimit field.
func (o *Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails) SetTotalClaimLimit(v string) {
    o.TotalClaimLimit = &v
}

func (o Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.ProductId) {
        toSerialize["product_id"] = o.ProductId
    }
    if !utils.IsNil(o.SkuId) {
        toSerialize["sku_id"] = o.SkuId
    }
    if !utils.IsNil(o.TotalClaimLimit) {
        toSerialize["total_claim_limit"] = o.TotalClaimLimit
    }
    return toSerialize, nil
}

type NullablePromotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails struct {
	value *Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails
	isSet bool
}

func (v NullablePromotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails) Get() *Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails {
	return v.value
}

func (v *NullablePromotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails) Set(val *Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails) {
	v.value = val
	v.isSet = true
}

func (v NullablePromotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails) IsSet() bool {
	return v.isSet
}

func (v *NullablePromotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails(val *Promotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails) *NullablePromotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails {
	return &NullablePromotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails{value: val, isSet: true}
}

func (v NullablePromotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromotion202309UpdateActivityRequestBodyDiscountGiftDiscountGiftInfosGiftDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


