/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion_v202309

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Promotion202309UpdateActivityRequestBodyParticipationLimit type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Promotion202309UpdateActivityRequestBodyParticipationLimit{}

// Promotion202309UpdateActivityRequestBodyParticipationLimit struct for Promotion202309UpdateActivityRequestBodyParticipationLimit
type Promotion202309UpdateActivityRequestBodyParticipationLimit struct {
    // Determines whether the promotion activity limits the number of times each buyer can receive its benefit. e.g.: - `BUYER_NO_LIMIT`: No limit for buyer​s. Buyers can benefit from this promotion across multiple orders. - `BUYER_LIMIT_ONLY_ONE`: Buyers can benefit from this promotion activity for no more than one order. ​Default: `BUYER_NO_LIMIT`
    Type *string `json:"type,omitempty"`
}

// NewPromotion202309UpdateActivityRequestBodyParticipationLimit instantiates a new Promotion202309UpdateActivityRequestBodyParticipationLimit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromotion202309UpdateActivityRequestBodyParticipationLimit() *Promotion202309UpdateActivityRequestBodyParticipationLimit {
    this := Promotion202309UpdateActivityRequestBodyParticipationLimit{}
    return &this
}

// NewPromotion202309UpdateActivityRequestBodyParticipationLimitWithDefaults instantiates a new Promotion202309UpdateActivityRequestBodyParticipationLimit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromotion202309UpdateActivityRequestBodyParticipationLimitWithDefaults() *Promotion202309UpdateActivityRequestBodyParticipationLimit {
    this := Promotion202309UpdateActivityRequestBodyParticipationLimit{}
    return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Promotion202309UpdateActivityRequestBodyParticipationLimit) GetType() string {
    if o == nil || utils.IsNil(o.Type) {
        var ret string
        return ret
    }
    return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Promotion202309UpdateActivityRequestBodyParticipationLimit) GetTypeOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Type) {
        return nil, false
    }
    return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Promotion202309UpdateActivityRequestBodyParticipationLimit) HasType() bool {
    if o != nil && !utils.IsNil(o.Type) {
        return true
    }

    return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Promotion202309UpdateActivityRequestBodyParticipationLimit) SetType(v string) {
    o.Type = &v
}

func (o Promotion202309UpdateActivityRequestBodyParticipationLimit) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Promotion202309UpdateActivityRequestBodyParticipationLimit) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Type) {
        toSerialize["type"] = o.Type
    }
    return toSerialize, nil
}

type NullablePromotion202309UpdateActivityRequestBodyParticipationLimit struct {
	value *Promotion202309UpdateActivityRequestBodyParticipationLimit
	isSet bool
}

func (v NullablePromotion202309UpdateActivityRequestBodyParticipationLimit) Get() *Promotion202309UpdateActivityRequestBodyParticipationLimit {
	return v.value
}

func (v *NullablePromotion202309UpdateActivityRequestBodyParticipationLimit) Set(val *Promotion202309UpdateActivityRequestBodyParticipationLimit) {
	v.value = val
	v.isSet = true
}

func (v NullablePromotion202309UpdateActivityRequestBodyParticipationLimit) IsSet() bool {
	return v.isSet
}

func (v *NullablePromotion202309UpdateActivityRequestBodyParticipationLimit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromotion202309UpdateActivityRequestBodyParticipationLimit(val *Promotion202309UpdateActivityRequestBodyParticipationLimit) *NullablePromotion202309UpdateActivityRequestBodyParticipationLimit {
	return &NullablePromotion202309UpdateActivityRequestBodyParticipationLimit{value: val, isSet: true}
}

func (v NullablePromotion202309UpdateActivityRequestBodyParticipationLimit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromotion202309UpdateActivityRequestBodyParticipationLimit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


