/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202312

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202312CheckListingPrerequisitesResponseData type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202312CheckListingPrerequisitesResponseData{}

// Product202312CheckListingPrerequisitesResponseData struct for Product202312CheckListingPrerequisitesResponseData
type Product202312CheckListingPrerequisitesResponseData struct {
    // A list of results from checking whether a shop satisfies TikTok Shop requirements.
    CheckResults []Product202312CheckListingPrerequisitesResponseDataCheckResults `json:"check_results,omitempty"`
}

// NewProduct202312CheckListingPrerequisitesResponseData instantiates a new Product202312CheckListingPrerequisitesResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202312CheckListingPrerequisitesResponseData() *Product202312CheckListingPrerequisitesResponseData {
    this := Product202312CheckListingPrerequisitesResponseData{}
    return &this
}

// NewProduct202312CheckListingPrerequisitesResponseDataWithDefaults instantiates a new Product202312CheckListingPrerequisitesResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202312CheckListingPrerequisitesResponseDataWithDefaults() *Product202312CheckListingPrerequisitesResponseData {
    this := Product202312CheckListingPrerequisitesResponseData{}
    return &this
}

// GetCheckResults returns the CheckResults field value if set, zero value otherwise.
func (o *Product202312CheckListingPrerequisitesResponseData) GetCheckResults() []Product202312CheckListingPrerequisitesResponseDataCheckResults {
    if o == nil || utils.IsNil(o.CheckResults) {
        var ret []Product202312CheckListingPrerequisitesResponseDataCheckResults
        return ret
    }
    return o.CheckResults
}

// GetCheckResultsOk returns a tuple with the CheckResults field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202312CheckListingPrerequisitesResponseData) GetCheckResultsOk() ([]Product202312CheckListingPrerequisitesResponseDataCheckResults, bool) {
    if o == nil || utils.IsNil(o.CheckResults) {
        return nil, false
    }
    return o.CheckResults, true
}

// HasCheckResults returns a boolean if a field has been set.
func (o *Product202312CheckListingPrerequisitesResponseData) HasCheckResults() bool {
    if o != nil && !utils.IsNil(o.CheckResults) {
        return true
    }

    return false
}

// SetCheckResults gets a reference to the given []Product202312CheckListingPrerequisitesResponseDataCheckResults and assigns it to the CheckResults field.
func (o *Product202312CheckListingPrerequisitesResponseData) SetCheckResults(v []Product202312CheckListingPrerequisitesResponseDataCheckResults) {
    o.CheckResults = v
}

func (o Product202312CheckListingPrerequisitesResponseData) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202312CheckListingPrerequisitesResponseData) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.CheckResults) {
        toSerialize["check_results"] = o.CheckResults
    }
    return toSerialize, nil
}

type NullableProduct202312CheckListingPrerequisitesResponseData struct {
	value *Product202312CheckListingPrerequisitesResponseData
	isSet bool
}

func (v NullableProduct202312CheckListingPrerequisitesResponseData) Get() *Product202312CheckListingPrerequisitesResponseData {
	return v.value
}

func (v *NullableProduct202312CheckListingPrerequisitesResponseData) Set(val *Product202312CheckListingPrerequisitesResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202312CheckListingPrerequisitesResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202312CheckListingPrerequisitesResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202312CheckListingPrerequisitesResponseData(val *Product202312CheckListingPrerequisitesResponseData) *NullableProduct202312CheckListingPrerequisitesResponseData {
	return &NullableProduct202312CheckListingPrerequisitesResponseData{value: val, isSet: true}
}

func (v NullableProduct202312CheckListingPrerequisitesResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202312CheckListingPrerequisitesResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


