/*
tiktok shop openapi

sdk for apis

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_v202407

import (
    "encoding/json"
    "tiktokshop/open/sdk_golang/utils"
)

            // checks if the Product202407SearchSizeChartsResponseDataSizeChartImages type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Product202407SearchSizeChartsResponseDataSizeChartImages{}

// Product202407SearchSizeChartsResponseDataSizeChartImages struct for Product202407SearchSizeChartsResponseDataSizeChartImages
type Product202407SearchSizeChartsResponseDataSizeChartImages struct {
    // The language of the size chart image.
    Locale *string `json:"locale,omitempty"`
    // The URI to identify the image in API requests and responses.
    Uri *string `json:"uri,omitempty"`
    // The URL to access and view the image.
    Url *string `json:"url,omitempty"`
}

// NewProduct202407SearchSizeChartsResponseDataSizeChartImages instantiates a new Product202407SearchSizeChartsResponseDataSizeChartImages object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProduct202407SearchSizeChartsResponseDataSizeChartImages() *Product202407SearchSizeChartsResponseDataSizeChartImages {
    this := Product202407SearchSizeChartsResponseDataSizeChartImages{}
    return &this
}

// NewProduct202407SearchSizeChartsResponseDataSizeChartImagesWithDefaults instantiates a new Product202407SearchSizeChartsResponseDataSizeChartImages object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProduct202407SearchSizeChartsResponseDataSizeChartImagesWithDefaults() *Product202407SearchSizeChartsResponseDataSizeChartImages {
    this := Product202407SearchSizeChartsResponseDataSizeChartImages{}
    return &this
}

// GetLocale returns the Locale field value if set, zero value otherwise.
func (o *Product202407SearchSizeChartsResponseDataSizeChartImages) GetLocale() string {
    if o == nil || utils.IsNil(o.Locale) {
        var ret string
        return ret
    }
    return *o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202407SearchSizeChartsResponseDataSizeChartImages) GetLocaleOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Locale) {
        return nil, false
    }
    return o.Locale, true
}

// HasLocale returns a boolean if a field has been set.
func (o *Product202407SearchSizeChartsResponseDataSizeChartImages) HasLocale() bool {
    if o != nil && !utils.IsNil(o.Locale) {
        return true
    }

    return false
}

// SetLocale gets a reference to the given string and assigns it to the Locale field.
func (o *Product202407SearchSizeChartsResponseDataSizeChartImages) SetLocale(v string) {
    o.Locale = &v
}

// GetUri returns the Uri field value if set, zero value otherwise.
func (o *Product202407SearchSizeChartsResponseDataSizeChartImages) GetUri() string {
    if o == nil || utils.IsNil(o.Uri) {
        var ret string
        return ret
    }
    return *o.Uri
}

// GetUriOk returns a tuple with the Uri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202407SearchSizeChartsResponseDataSizeChartImages) GetUriOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Uri) {
        return nil, false
    }
    return o.Uri, true
}

// HasUri returns a boolean if a field has been set.
func (o *Product202407SearchSizeChartsResponseDataSizeChartImages) HasUri() bool {
    if o != nil && !utils.IsNil(o.Uri) {
        return true
    }

    return false
}

// SetUri gets a reference to the given string and assigns it to the Uri field.
func (o *Product202407SearchSizeChartsResponseDataSizeChartImages) SetUri(v string) {
    o.Uri = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *Product202407SearchSizeChartsResponseDataSizeChartImages) GetUrl() string {
    if o == nil || utils.IsNil(o.Url) {
        var ret string
        return ret
    }
    return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Product202407SearchSizeChartsResponseDataSizeChartImages) GetUrlOk() (*string, bool) {
    if o == nil || utils.IsNil(o.Url) {
        return nil, false
    }
    return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *Product202407SearchSizeChartsResponseDataSizeChartImages) HasUrl() bool {
    if o != nil && !utils.IsNil(o.Url) {
        return true
    }

    return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *Product202407SearchSizeChartsResponseDataSizeChartImages) SetUrl(v string) {
    o.Url = &v
}

func (o Product202407SearchSizeChartsResponseDataSizeChartImages) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
        return []byte{}, err
    }
    return json.Marshal(toSerialize)
}

func (o Product202407SearchSizeChartsResponseDataSizeChartImages) ToMap() (map[string]interface{}, error) {
    toSerialize := map[string]interface{}{}
    if !utils.IsNil(o.Locale) {
        toSerialize["locale"] = o.Locale
    }
    if !utils.IsNil(o.Uri) {
        toSerialize["uri"] = o.Uri
    }
    if !utils.IsNil(o.Url) {
        toSerialize["url"] = o.Url
    }
    return toSerialize, nil
}

type NullableProduct202407SearchSizeChartsResponseDataSizeChartImages struct {
	value *Product202407SearchSizeChartsResponseDataSizeChartImages
	isSet bool
}

func (v NullableProduct202407SearchSizeChartsResponseDataSizeChartImages) Get() *Product202407SearchSizeChartsResponseDataSizeChartImages {
	return v.value
}

func (v *NullableProduct202407SearchSizeChartsResponseDataSizeChartImages) Set(val *Product202407SearchSizeChartsResponseDataSizeChartImages) {
	v.value = val
	v.isSet = true
}

func (v NullableProduct202407SearchSizeChartsResponseDataSizeChartImages) IsSet() bool {
	return v.isSet
}

func (v *NullableProduct202407SearchSizeChartsResponseDataSizeChartImages) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProduct202407SearchSizeChartsResponseDataSizeChartImages(val *Product202407SearchSizeChartsResponseDataSizeChartImages) *NullableProduct202407SearchSizeChartsResponseDataSizeChartImages {
	return &NullableProduct202407SearchSizeChartsResponseDataSizeChartImages{value: val, isSet: true}
}

func (v NullableProduct202407SearchSizeChartsResponseDataSizeChartImages) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProduct202407SearchSizeChartsResponseDataSizeChartImages) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


